# Test registry for kerasformers.
#
# Each entry describes one parametrized test case for the integration suite:
# - `module` + `model_cls`: how to import the class under test.
# - `init_kwargs`: arguments to instantiate the model. For classification
#   models, these are the architectural params (matching a *_MODEL_CONFIG
#   entry) plus a `num_classes`. The pretrained-weights loading path is
#   intentionally NOT exercised here — these tests stay offline.
# - `input_shape` OR `input_factory`: how the integration tests build a
#   dummy input batch. `input_factory` is for models whose input is a dict
#   (VLMs, SAM, OwlViT).
# - `expected_output_shape`: shape (or dict-of-shapes / list-of-shapes)
#   that the model's output should have. Use `None` for dynamic shapes.

MODEL_TEST_CONFIGS = {
    # ---------- Classification: XImageClassify (full classifier with head) ----------
    "CaiTImageClassify": {
        "module": "kerasformers.models.cait",
        "model_cls": "CaiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "embed_dim": 192,
            "depth": 2,
            "num_heads": 4,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvMixerImageClassify": {
        "module": "kerasformers.models.convmixer",
        "model_cls": "ConvMixerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "dim": 128,
            "depth": 2,
            "patch_size": 4,
            "kernel_size": 3,
            "activation": "gelu",
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvNeXtImageClassify": {
        "module": "kerasformers.models.convnext",
        "model_cls": "ConvNeXtImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "projection_dims": (40, 80, 160, 320),
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvNeXtV2ImageClassify": {
        "module": "kerasformers.models.convnextv2",
        "model_cls": "ConvNeXtV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "projection_dims": (40, 80, 160, 320),
            "use_conv": True,
            "use_grn": True,
            "layer_scale_init_value": None,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "DeiTImageClassify": {
        "module": "kerasformers.models.deit",
        "model_cls": "DeiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "DenseNetImageClassify": {
        "module": "kerasformers.models.densenet",
        "model_cls": "DenseNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_blocks": (2, 2, 2, 2),
            "growth_rate": 32,
            "initial_filter": 64,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientFormerImageClassify": {
        "module": "kerasformers.models.efficientformer",
        "model_cls": "EfficientFormerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (1, 1, 2, 1),
            "embed_dims": (48, 96, 224, 448),
            "num_vit": 1,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetImageClassify": {
        "module": "kerasformers.models.efficientnet",
        "model_cls": "EfficientNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "dropout_rate": 0.0,
            "default_size": 32,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetLiteImageClassify": {
        "module": "kerasformers.models.efficientnet_lite",
        "model_cls": "EfficientNetLiteImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "dropout_rate": 0.0,
            "default_size": 32,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetV2ImageClassify": {
        "module": "kerasformers.models.efficientnetv2",
        "model_cls": "EfficientNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "default_size": 32,
            "block_arch": "EfficientNetV2S",
            "head_filters": 1280,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "FlexiViTImageClassify": {
        "module": "kerasformers.models.flexivit",
        "model_cls": "FlexiViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "no_embed_class": True,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionNextImageClassify": {
        "module": "kerasformers.models.inception_next",
        "model_cls": "InceptionNextImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "num_filters": (40, 80, 160, 320),
            "mlp_ratios": (4, 4, 4, 3),
            "band_kernel_size": 9,
            "branch_ratio": 0.25,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionResNetV2ImageClassify": {
        "module": "kerasformers.models.inception_resnetv2",
        "model_cls": "InceptionResNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": 75,
            "input_shape": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionV3ImageClassify": {
        "module": "kerasformers.models.inceptionv3",
        "model_cls": "InceptionV3ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": 75,
            "input_shape": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionV4ImageClassify": {
        "module": "kerasformers.models.inceptionv4",
        "model_cls": "InceptionV4ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": 75,
            "input_shape": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "MaxViTImageClassify": {
        "module": "kerasformers.models.maxvit",
        "model_cls": "MaxViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "stem_width": 64,
            "depths": (2, 2, 2, 2),
            "embed_dim": (64, 128, 256, 512),
            "num_heads": (2, 4, 8, 16),
            "window_size": 2,
            "image_size": 64,
            "input_shape": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "MiTImageClassify": {
        "module": "kerasformers.models.mit",
        "model_cls": "MiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dims": (32, 64, 160, 256),
            "depths": (1, 1, 1, 1),
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MLPMixerImageClassify": {
        "module": "kerasformers.models.mlp_mixer",
        "model_cls": "MLPMixerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "num_blocks": 2,
            "embed_dim": 192,
            "mlp_ratio": (0.5, 4.0),
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileNetV2ImageClassify": {
        "module": "kerasformers.models.mobilenetv2",
        "model_cls": "MobileNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_multiplier": 0.5,
            "depth_multiplier": 1.0,
            "fix_channels": False,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileNetV3ImageClassify": {
        "module": "kerasformers.models.mobilenetv3",
        "model_cls": "MobileNetV3ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_multiplier": 0.5,
            "depth_multiplier": 1.0,
            "config": "small",
            "minimal": False,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileViTImageClassify": {
        "module": "kerasformers.models.mobilevit",
        "model_cls": "MobileViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "initial_dims": 16,
            "head_dims": 320,
            "block_dims": [16, 24, 48, 64, 80],
            "expansion_ratio": [2.0, 2.0, 2.0, 2.0, 2.0],
            "attention_dims": [None, None, 64, 80, 96],
            "image_size": 64,
            "input_shape": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileViTV2ImageClassify": {
        "module": "kerasformers.models.mobilevitv2",
        "model_cls": "MobileViTV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "multiplier": 0.5,
            "image_size": 64,
            "input_shape": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "NextViTImageClassify": {
        "module": "kerasformers.models.nextvit",
        "model_cls": "NextViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (1, 1, 5, 1),
            "stem_chs": (64, 32, 64),
            "head_dim": 32,
            "mix_block_ratio": 0.75,
            "sr_ratios": (8, 4, 2, 1),
            "drop_path_rate": 0.0,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "PiTImageClassify": {
        "module": "kerasformers.models.pit",
        "model_cls": "PiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "stride": 8,
            "embed_dim": (96, 192, 384),
            "depth": (1, 2, 1),
            "heads": (2, 4, 8),
            "mlp_ratio": 4,
            "distilled": False,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "PoolFormerImageClassify": {
        "module": "kerasformers.models.poolformer",
        "model_cls": "PoolFormerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dims": (64, 128, 320, 512),
            "num_blocks": (1, 1, 2, 1),
            "init_scale": 1e-5,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "Res2NetImageClassify": {
        "module": "kerasformers.models.res2net",
        "model_cls": "Res2NetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depth": [1, 1, 1, 1],
            "base_width": 14,
            "scale": 8,
            "cardinality": 1,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResMLPImageClassify": {
        "module": "kerasformers.models.resmlp",
        "model_cls": "ResMLPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "embed_dim": 384,
            "depth": 2,
            "mlp_ratio": 4,
            "init_values": 1e-4,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNetImageClassify": {
        "module": "kerasformers.models.resnet",
        "model_cls": "ResNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "block_repeats": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNetV2ImageClassify": {
        "module": "kerasformers.models.resnetv2",
        "model_cls": "ResNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "block_repeats": [1, 1, 1, 1],
            "width_factor": 1,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNeXtImageClassify": {
        "module": "kerasformers.models.resnext",
        "model_cls": "ResNeXtImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "block_repeats": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "groups": 32,
            "width_factor": 2,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SENetImageClassify": {
        "module": "kerasformers.models.senet",
        "model_cls": "SENetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "block_repeats": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "senet": True,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SwinImageClassify": {
        "module": "kerasformers.models.swin",
        "model_cls": "SwinImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "window_size": 2,
            "embed_dim": 96,
            "depths": (2, 2, 2, 2),
            "num_heads": (3, 6, 12, 24),
            "pretrain_size": 32,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SwinV2ImageClassify": {
        "module": "kerasformers.models.swinv2",
        "model_cls": "SwinV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dim": 96,
            "depths": (2, 2, 2, 2),
            "num_heads": (3, 6, 12, 24),
            "window_size": 8,
            "pretrain_size": 64,
            "pretrained_window_size": 0,
            "image_size": 64,
            "input_shape": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "VGGImageClassify": {
        "module": "kerasformers.models.vgg",
        "model_cls": "VGGImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_filters": [64, "M", 128, "M", 256, "M"],
            "batch_norm": False,
            "image_size": 64,
            "input_shape": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "ViTImageClassify": {
        "module": "kerasformers.models.vit",
        "model_cls": "ViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "mlp_ratio": 4.0,
            "qkv_bias": True,
            "qk_norm": False,
            "image_size": 32,
            "input_shape": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "XceptionImageClassify": {
        "module": "kerasformers.models.xception",
        "model_cls": "XceptionImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": 71,
            "input_shape": (71, 71, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 71, 71, 3),
        "expected_output_shape": (2, 1000),
    },
    # ---------- Self-supervised vision backbones ----------
    "DinoViTBackbone": {
        "module": "kerasformers.models.dino",
        "model_cls": "DinoViTBackbone",
        "model_type": "backbone",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoResNetBackbone": {
        "module": "kerasformers.models.dino",
        "model_cls": "DinoResNetBackbone",
        "model_type": "backbone",
        "init_kwargs": {
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoV2Backbone": {
        "module": "kerasformers.models.dino_v2",
        "model_cls": "DinoV2Backbone",
        "model_type": "backbone",
        "init_kwargs": {
            "patch_size": 14,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "input_shape": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": None,
    },
    "DinoV3ViTBackbone": {
        "module": "kerasformers.models.dino_v3",
        "model_cls": "DinoV3ViTBackbone",
        "model_type": "backbone",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoV3ConvNeXtBackbone": {
        "module": "kerasformers.models.dino_v3",
        "model_cls": "DinoV3ConvNeXtBackbone",
        "model_type": "backbone",
        "init_kwargs": {
            "depths": [2, 2, 2, 2],
            "projection_dims": [96, 192, 384, 768],
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    # ---------- Object detection ----------
    "DFineDetect": {
        "module": "kerasformers.models.dfine",
        "model_cls": "DFineDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "stem_channels": (3, 16, 16),
            "stage_in_channels": (16, 64, 256, 512),
            "stage_mid_channels": (16, 32, 64, 128),
            "stage_out_channels": (64, 256, 512, 1024),
            "stage_num_blocks": (1, 1, 2, 1),
            "stage_numb_of_layers": (3, 3, 3, 3),
            "use_lab": True,
            "encoder_in_channels": (256, 512, 1024),
            "hidden_expansion": 0.5,
            "decoder_layers": 3,
            "decoder_n_points": [3, 6, 3],
            "input_shape": (320, 320, 3),
            "num_labels": 80,
        },
        "input_shape": (2, 320, 320, 3),
        "expected_output_shape": {
            "logits": (2, 300, 80),
            "pred_boxes": (2, 300, 4),
        },
    },
    "DETRDetect": {
        "module": "kerasformers.models.detr",
        "model_cls": "DETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_variant": "ResNet50",
            "input_shape": (32, 32, 3),
            "num_classes": 92,
            "num_queries": 10,
            "include_normalization": False,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": {
            "logits": (2, 10, 92),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RTDETRDetect": {
        "module": "kerasformers.models.rt_detr",
        "model_cls": "RTDETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_hidden_sizes": (64, 128, 256, 512),
            "backbone_block_repeats": (2, 2, 2, 2),
            "backbone_layer_type": "basic",
            "encoder_in_channels": (128, 256, 512),
            "hidden_expansion": 0.5,
            "decoder_layers": 3,
            "input_shape": (128, 128, 3),
            "num_queries": 10,
            "num_labels": 80,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": {
            "logits": (2, 10, 80),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RTDETRV2Detect": {
        "module": "kerasformers.models.rt_detr_v2",
        "model_cls": "RTDETRV2Detect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_hidden_sizes": (64, 128, 256, 512),
            "backbone_block_repeats": (2, 2, 2, 2),
            "backbone_layer_type": "basic",
            "encoder_in_channels": (128, 256, 512),
            "hidden_expansion": 0.5,
            "decoder_layers": 3,
            "input_shape": (128, 128, 3),
            "num_queries": 10,
            "num_labels": 80,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": {
            "logits": (2, 10, 80),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RFDETRDetect": {
        "module": "kerasformers.models.rf_detr",
        "model_cls": "RFDETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "patch_size": 16,
            "num_windows": 2,
            "positional_encoding_size": 24,
            "resolution": 384,
            "dec_layers": 2,
            "num_queries": 10,
            "num_classes": 91,
            "input_shape": (256, 256, 3),
        },
        "input_shape": (2, 256, 256, 3),
        "expected_output_shape": {
            "pred_logits": (2, 10, 91),
            "pred_boxes": (2, 10, 4),
        },
    },
    # ---------- Depth estimation ----------
    "DepthAnythingV1DepthEstimation": {
        "module": "kerasformers.models.depth_anything_v1",
        "model_cls": "DepthAnythingV1DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "input_shape": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    "DepthAnythingV2DepthEstimation": {
        "module": "kerasformers.models.depth_anything_v2",
        "model_cls": "DepthAnythingV2DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "input_shape": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    "DepthAnythingV2DepthEstimation_metric": {
        "module": "kerasformers.models.depth_anything_v2",
        "model_cls": "DepthAnythingV2DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "input_shape": (42, 42, 3),
            "depth_estimation_type": "metric",
            "max_depth": 20.0,
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    # ---------- Semantic / universal segmentation ----------
    "DeepLabV3Segment": {
        "module": "kerasformers.models.deeplabv3",
        "model_cls": "DeepLabV3Segment",
        "model_type": "segmentation",
        "init_kwargs": {
            "backbone_variant": "ResNet50",
            "input_shape": (64, 64, 3),
            "num_classes": 21,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 64, 64, 21),
    },
    "EoMTUniversalSegment": {
        "module": "kerasformers.models.eomt",
        "model_cls": "EoMTUniversalSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "hidden_size": 384,
            "num_hidden_layers": 2,
            "num_attention_heads": 6,
            "num_blocks": 1,
            "layerscale_value": 1.0,
            "input_shape": (64, 64, 3),
            "num_queries": 100,
            "num_labels": 133,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": {
            "class_logits": (2, 100, 134),
            "mask_logits": (2, 100, 16, 16),
        },
    },
    "MobileViTSegment": {
        "module": "kerasformers.models.mobilevit",
        "model_cls": "MobileViTSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "initial_dims": 16,
            "head_dims": 320,
            "block_dims": [16, 24, 48, 64, 80],
            "expansion_ratio": [2.0, 2.0, 2.0, 2.0, 2.0],
            "attention_dims": [None, None, 64, 80, 96],
            "image_size": 128,
            "output_stride": 16,
            "input_shape": (128, 128, 3),
            "num_classes": 21,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": (2, 8, 8, 21),
    },
    "MobileViTV2Segment": {
        "module": "kerasformers.models.mobilevitv2",
        "model_cls": "MobileViTV2Segment",
        "model_type": "segmentation",
        "init_kwargs": {
            "multiplier": 0.5,
            "image_size": 128,
            "output_stride": 16,
            "input_shape": (128, 128, 3),
            "num_classes": 21,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": (2, 8, 8, 21),
    },
    "SegFormerSegment": {
        "module": "kerasformers.models.segformer",
        "model_cls": "SegFormerSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "input_shape": (32, 32, 3),
            "num_classes": 150,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 32, 32, 150),
    },
    # ---------- Promptable segmentation ----------
    "SAMModel": {
        "module": "kerasformers.models.sam",
        "model_cls": "SAMModel",
        "model_type": "backbone",
        "init_kwargs": {
            "vision_hidden_size": 64,
            "vision_num_hidden_layers": 2,
            "vision_num_attention_heads": 2,
            "vision_mlp_dim": 128,
            "vision_global_attn_indexes": (1,),
            "input_shape": (64, 64, 3),
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": None,
    },
    "SAMPromptableSegment": {
        "module": "kerasformers.models.sam",
        "model_cls": "SAMPromptableSegment",
        "model_type": "promptable_segmentation",
        "init_kwargs": {
            "vision_hidden_size": 64,
            "vision_num_hidden_layers": 2,
            "vision_num_attention_heads": 2,
            "vision_mlp_dim": 128,
            "vision_global_attn_indexes": (1,),
            "input_shape": (64, 64, 3),
        },
        "input_factory": "sam_input",
        "input_factory_kwargs": {"image_size": 64},
        "expected_output_shape": {
            "pred_masks": None,
            "iou_scores": None,
        },
    },
    "SAM2Model": {
        "module": "kerasformers.models.sam2",
        "model_cls": "SAM2Model",
        "model_type": "backbone",
        "init_kwargs": {
            "hidden_size": 32,
            "blocks_per_stage": (1, 1, 1, 1),
            "embed_dim_per_stage": (32, 64, 128, 256),
            "num_attention_heads_per_stage": (1, 1, 2, 2),
            "window_size_per_stage": (4, 2, 4, 2),
            "global_attention_blocks": (),
            "backbone_channel_list": (256, 128, 64, 32),
            "input_shape": (64, 64, 3),
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": None,
    },
    "SAM2PromptableSegment": {
        "module": "kerasformers.models.sam2",
        "model_cls": "SAM2PromptableSegment",
        "model_type": "promptable_segmentation",
        "init_kwargs": {
            "hidden_size": 32,
            "blocks_per_stage": (1, 1, 1, 1),
            "embed_dim_per_stage": (32, 64, 128, 256),
            "num_attention_heads_per_stage": (1, 1, 2, 2),
            "window_size_per_stage": (4, 2, 4, 2),
            "global_attention_blocks": (),
            "backbone_channel_list": (256, 128, 64, 32),
            "input_shape": (64, 64, 3),
        },
        "input_factory": "sam_input",
        "input_factory_kwargs": {"image_size": 64},
        "expected_output_shape": {
            "pred_masks": None,
            "iou_scores": None,
            "object_score_logits": None,
        },
    },
    # ---------- Vision-language (CLIP family) ----------
    "CLIPModel": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPModel",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "context_length": 16,
            "vocab_size": 128,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": None,
    },
    "CLIPZeroShotClassify": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "context_length": 16,
            "vocab_size": 128,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "CLIPImageClassify": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_labels": 10,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (SigLIP family) ----------
    "SigLIPModel": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPModel",
        "model_type": "vlm",
        "init_kwargs": {
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocabulary_size": 128,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_sequence_length": 16,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": None,
    },
    "SigLIPZeroShotClassify": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocabulary_size": 128,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_sequence_length": 16,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "SigLIPImageClassify": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_labels": 10,
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (SigLIP 2 family) ----------
    "SigLIP2Model": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2Model",
        "model_type": "vlm",
        "init_kwargs": {
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocabulary_size": 256,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_sequence_length": 16,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": None,
    },
    "SigLIP2ZeroShotClassify": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2ZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocabulary_size": 256,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_sequence_length": 16,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "SigLIP2ImageClassify": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_labels": 10,
            "image_resolution": 32,
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (MetaCLIP 2) ----------
    "MetaClip2Model": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2Model",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "context_length": 16,
            "vocab_size": 256,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": None,
    },
    "MetaClip2ZeroShotClassify": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2ZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "context_length": 16,
            "vocab_size": 256,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
            "input_shape": (32, 32, 3),
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "context_length": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "MetaClip2ImageClassify": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_labels": 10,
            "image_resolution": 32,
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "input_shape": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Audio (Whisper) ----------
    "WhisperModel": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperModel",
        "model_type": "audio",
        "init_kwargs": {
            "d_model": 64,
            "encoder_layers": 1,
            "decoder_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "max_target_positions": 10,
            "vocab_size": 128,
        },
        "input_factory": "whisper_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "mel_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 20, 64),
            "logits": (2, 5, 128),
        },
    },
    "WhisperSpeechToText": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperSpeechToText",
        "model_type": "audio",
        "init_kwargs": {
            "d_model": 64,
            "encoder_layers": 1,
            "decoder_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "max_target_positions": 10,
            "vocab_size": 128,
        },
        "input_factory": "whisper_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "mel_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 20, 64),
            "logits": (2, 5, 128),
        },
    },
    "WhisperAudioClassify": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperAudioClassify",
        "model_type": "audio",
        "init_kwargs": {
            "d_model": 64,
            "encoder_layers": 1,
            "encoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "num_labels": 10,
            "classifier_proj_size": 32,
        },
        "input_factory": "whisper_audio_input",
        "input_factory_kwargs": {"num_mel_bins": 80, "mel_length": 40},
        "expected_output_shape": (2, 10),
    },
    "OwlViTDetect": {
        "module": "kerasformers.models.owlvit",
        "model_cls": "OwlViTDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "vision_image_size": 64,
            "vision_patch_size": 16,
            "vision_hidden_size": 32,
            "vision_intermediate_size": 64,
            "vision_num_hidden_layers": 2,
            "vision_num_attention_heads": 2,
            "text_hidden_size": 16,
            "text_intermediate_size": 32,
            "text_num_attention_heads": 2,
            "projection_dim": 16,
        },
        "input_factory": "owlvit_input",
        "input_factory_kwargs": {
            "image_size": 64,
            "context_length": 16,
            "num_queries": 2,
        },
        "expected_output_shape": {
            "logits": (2, 16, 2),
            "pred_boxes": (2, 16, 4),
        },
    },
}


def get_all_model_ids():
    return list(MODEL_TEST_CONFIGS.keys())


def get_models_by_type(model_type):
    return {
        k: v for k, v in MODEL_TEST_CONFIGS.items() if v["model_type"] == model_type
    }


def import_model_class(config):
    import importlib

    module = importlib.import_module(config["module"])
    return getattr(module, config["model_cls"])


def create_test_input(config, batch_size=2):
    from tests.fixtures import dummy_inputs

    if "input_factory" in config:
        factory_fn = getattr(dummy_inputs, config["input_factory"])
        factory_kwargs = config.get("input_factory_kwargs", {})
        return factory_fn(batch_size=batch_size, **factory_kwargs)

    from keras import ops

    shape = config["input_shape"]
    return ops.ones(shape)
