# Test registry for kerasformers.
#
# Each entry describes one parametrized test case for the integration suite:
# - `module` + `model_cls`: how to import the class under test.
# - `init_kwargs`: arguments to instantiate the model. For classification
#   models, these are the architectural params (matching a *_MODEL_CONFIG
#   entry) plus a `num_classes`. The pretrained-weights loading path is
#   intentionally NOT exercised here — these tests stay offline.
# - `input_shape` OR `input_factory`: how the integration tests build a
#   dummy input batch. `input_factory` is for models whose input is a dict
#   (VLMs, SAM, OwlViT).
# - `expected_output_shape`: shape (or dict-of-shapes / list-of-shapes)
#   that the model's output should have. Use `None` for dynamic shapes.

MODEL_TEST_CONFIGS = {
    # ---------- Classification: XImageClassify (full classifier with head) ----------
    "CaiTImageClassify": {
        "module": "kerasformers.models.cait",
        "model_cls": "CaiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "embed_dim": 192,
            "depth": 2,
            "num_heads": 4,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvMixerImageClassify": {
        "module": "kerasformers.models.convmixer",
        "model_cls": "ConvMixerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "dim": 128,
            "depth": 2,
            "patch_size": 4,
            "kernel_size": 3,
            "activation": "gelu",
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvNeXtImageClassify": {
        "module": "kerasformers.models.convnext",
        "model_cls": "ConvNeXtImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "projection_dim": (40, 80, 160, 320),
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ConvNeXtV2ImageClassify": {
        "module": "kerasformers.models.convnextv2",
        "model_cls": "ConvNeXtV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "projection_dim": (40, 80, 160, 320),
            "use_conv": True,
            "use_grn": True,
            "layer_scale_init": None,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "DeiTImageClassify": {
        "module": "kerasformers.models.deit",
        "model_cls": "DeiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "DenseNetImageClassify": {
        "module": "kerasformers.models.densenet",
        "model_cls": "DenseNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "growth_rate": 32,
            "initial_filter": 64,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientFormerImageClassify": {
        "module": "kerasformers.models.efficientformer",
        "model_cls": "EfficientFormerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (1, 1, 2, 1),
            "embed_dim": (48, 96, 224, 448),
            "num_vit": 1,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetImageClassify": {
        "module": "kerasformers.models.efficientnet",
        "model_cls": "EfficientNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "dropout_rate": 0.0,
            "default_size": 32,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetLiteImageClassify": {
        "module": "kerasformers.models.efficientnet_lite",
        "model_cls": "EfficientNetLiteImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "dropout_rate": 0.0,
            "default_size": 32,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "EfficientNetV2ImageClassify": {
        "module": "kerasformers.models.efficientnetv2",
        "model_cls": "EfficientNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_coefficient": 1.0,
            "depth_coefficient": 1.0,
            "default_size": 32,
            "block_arch": "EfficientNetV2S",
            "head_filters": 1280,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "FlexiViTImageClassify": {
        "module": "kerasformers.models.flexivit",
        "model_cls": "FlexiViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "no_embed_class": True,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionNextImageClassify": {
        "module": "kerasformers.models.inception_next",
        "model_cls": "InceptionNextImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (2, 2, 2, 2),
            "num_filters": (40, 80, 160, 320),
            "mlp_ratios": (4, 4, 4, 3),
            "band_kernel_size": 9,
            "branch_ratio": 0.25,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionResNetV2ImageClassify": {
        "module": "kerasformers.models.inception_resnetv2",
        "model_cls": "InceptionResNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionV3ImageClassify": {
        "module": "kerasformers.models.inceptionv3",
        "model_cls": "InceptionV3ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "InceptionV4ImageClassify": {
        "module": "kerasformers.models.inceptionv4",
        "model_cls": "InceptionV4ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": (75, 75, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 75, 75, 3),
        "expected_output_shape": (2, 1000),
    },
    "MaxViTImageClassify": {
        "module": "kerasformers.models.maxvit",
        "model_cls": "MaxViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "stem_width": 64,
            "depths": (2, 2, 2, 2),
            "embed_dim": (64, 128, 256, 512),
            "num_heads": (2, 4, 8, 16),
            "window_size": 2,
            "image_size": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "MiTImageClassify": {
        "module": "kerasformers.models.mit",
        "model_cls": "MiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dim": (32, 64, 160, 256),
            "depths": (1, 1, 1, 1),
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MLPMixerImageClassify": {
        "module": "kerasformers.models.mlp_mixer",
        "model_cls": "MLPMixerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "depths": 2,
            "embed_dim": 192,
            "mlp_ratio": (0.5, 4.0),
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileNetV2ImageClassify": {
        "module": "kerasformers.models.mobilenetv2",
        "model_cls": "MobileNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_multiplier": 0.5,
            "depth_multiplier": 1.0,
            "fix_channels": False,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileNetV3ImageClassify": {
        "module": "kerasformers.models.mobilenetv3",
        "model_cls": "MobileNetV3ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "width_multiplier": 0.5,
            "depth_multiplier": 1.0,
            "config": "small",
            "minimal": False,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileViTImageClassify": {
        "module": "kerasformers.models.mobilevit",
        "model_cls": "MobileViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "initial_dims": 16,
            "head_dims": 320,
            "block_dims": [16, 24, 48, 64, 80],
            "expansion_ratio": [2.0, 2.0, 2.0, 2.0, 2.0],
            "attention_dims": [None, None, 64, 80, 96],
            "image_size": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "MobileViTV2ImageClassify": {
        "module": "kerasformers.models.mobilevitv2",
        "model_cls": "MobileViTV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "multiplier": 0.5,
            "image_size": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "NextViTImageClassify": {
        "module": "kerasformers.models.nextvit",
        "model_cls": "NextViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": (1, 1, 5, 1),
            "stem_chs": (64, 32, 64),
            "head_dim": 32,
            "mix_block_ratio": 0.75,
            "sr_ratios": (8, 4, 2, 1),
            "drop_path_rate": 0.0,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "PiTImageClassify": {
        "module": "kerasformers.models.pit",
        "model_cls": "PiTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "stride": 8,
            "embed_dim": (96, 192, 384),
            "depth": (1, 2, 1),
            "heads": (2, 4, 8),
            "mlp_ratio": 4,
            "distilled": False,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "PoolFormerImageClassify": {
        "module": "kerasformers.models.poolformer",
        "model_cls": "PoolFormerImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dim": (64, 128, 320, 512),
            "depths": (1, 1, 2, 1),
            "init_scale": 1e-5,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "Res2NetImageClassify": {
        "module": "kerasformers.models.res2net",
        "model_cls": "Res2NetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depth": [1, 1, 1, 1],
            "base_width": 14,
            "scale": 8,
            "cardinality": 1,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResMLPImageClassify": {
        "module": "kerasformers.models.resmlp",
        "model_cls": "ResMLPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "embed_dim": 384,
            "depth": 2,
            "mlp_ratio": 4,
            "layer_scale_init": 1e-4,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNetImageClassify": {
        "module": "kerasformers.models.resnet",
        "model_cls": "ResNetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNetV2ImageClassify": {
        "module": "kerasformers.models.resnetv2",
        "model_cls": "ResNetV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": [1, 1, 1, 1],
            "width_factor": 1,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "ResNeXtImageClassify": {
        "module": "kerasformers.models.resnext",
        "model_cls": "ResNeXtImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "groups": 32,
            "width_factor": 2,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SENetImageClassify": {
        "module": "kerasformers.models.senet",
        "model_cls": "SENetImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "depths": [1, 1, 1, 1],
            "filters": [64, 128, 256, 512],
            "senet": True,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SwinImageClassify": {
        "module": "kerasformers.models.swin",
        "model_cls": "SwinImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "window_size": 2,
            "embed_dim": 96,
            "depths": (2, 2, 2, 2),
            "num_heads": (3, 6, 12, 24),
            "pretrain_size": 32,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "SwinV2ImageClassify": {
        "module": "kerasformers.models.swinv2",
        "model_cls": "SwinV2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "embed_dim": 96,
            "depths": (2, 2, 2, 2),
            "num_heads": (3, 6, 12, 24),
            "window_size": 8,
            "pretrain_size": 64,
            "pretrained_window_size": 0,
            "image_size": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "VGGImageClassify": {
        "module": "kerasformers.models.vgg",
        "model_cls": "VGGImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_filters": [64, "M", 128, "M", 256, "M"],
            "batch_norm": False,
            "image_size": (64, 64, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 1000),
    },
    "ViTImageClassify": {
        "module": "kerasformers.models.vit",
        "model_cls": "ViTImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "patch_size": 16,
            "dim": 192,
            "depth": 2,
            "num_heads": 3,
            "mlp_ratio": 4.0,
            "qkv_bias": True,
            "qk_norm": False,
            "image_size": (32, 32, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 1000),
    },
    "XceptionImageClassify": {
        "module": "kerasformers.models.xception",
        "model_cls": "XceptionImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "image_size": (71, 71, 3),
            "num_classes": 1000,
        },
        "input_shape": (2, 71, 71, 3),
        "expected_output_shape": (2, 1000),
    },
    # ---------- Self-supervised vision backbones ----------
    "DinoViTModel": {
        "module": "kerasformers.models.dino",
        "model_cls": "DinoViTModel",
        "model_type": "backbone",
        "init_kwargs": {
            "as_backbone": True,
            "patch_size": 16,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "image_size": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoResNetModel": {
        "module": "kerasformers.models.dino",
        "model_cls": "DinoResNetModel",
        "model_type": "backbone",
        "init_kwargs": {
            "as_backbone": True,
            "image_size": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoV2Model": {
        "module": "kerasformers.models.dino_v2",
        "model_cls": "DinoV2Model",
        "model_type": "backbone",
        "init_kwargs": {
            "as_backbone": True,
            "patch_size": 14,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "image_size": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": None,
    },
    "DinoV3ViTModel": {
        "module": "kerasformers.models.dino_v3",
        "model_cls": "DinoV3ViTModel",
        "model_type": "backbone",
        "init_kwargs": {
            "as_backbone": True,
            "patch_size": 16,
            "dim": 384,
            "depth": 2,
            "num_heads": 6,
            "image_size": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    "DinoV3ConvNeXtModel": {
        "module": "kerasformers.models.dino_v3",
        "model_cls": "DinoV3ConvNeXtModel",
        "model_type": "backbone",
        "init_kwargs": {
            "as_backbone": True,
            "depths": [2, 2, 2, 2],
            "projection_dim": [96, 192, 384, 768],
            "image_size": (32, 32, 3),
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": None,
    },
    # ---------- Object detection ----------
    "DFineDetect": {
        "module": "kerasformers.models.dfine",
        "model_cls": "DFineDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "stem_channels": (3, 16, 16),
            "stage_in_channels": (16, 64, 256, 512),
            "stage_mid_channels": (16, 32, 64, 128),
            "stage_out_channels": (64, 256, 512, 1024),
            "stage_num_blocks": (1, 1, 2, 1),
            "stage_numb_of_layers": (3, 3, 3, 3),
            "use_lab": True,
            "encoder_in_channels": (256, 512, 1024),
            "hidden_expansion": 0.5,
            "decoder_num_layers": 3,
            "decoder_n_points": [3, 6, 3],
            "image_size": 320,
            "num_labels": 80,
        },
        "input_shape": (2, 320, 320, 3),
        "expected_output_shape": {
            "logits": (2, 300, 80),
            "pred_boxes": (2, 300, 4),
        },
    },
    "DETRDetect": {
        "module": "kerasformers.models.detr",
        "model_cls": "DETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_variant": "ResNet50",
            "image_size": 32,
            "num_classes": 92,
            "num_queries": 10,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": {
            "logits": (2, 10, 92),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RTDETRDetect": {
        "module": "kerasformers.models.rt_detr",
        "model_cls": "RTDETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_hidden_sizes": (64, 128, 256, 512),
            "backbone_block_repeats": (2, 2, 2, 2),
            "backbone_layer_type": "basic",
            "encoder_in_channels": (128, 256, 512),
            "hidden_expansion": 0.5,
            "decoder_num_layers": 3,
            "image_size": 128,
            "num_queries": 10,
            "num_labels": 80,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": {
            "logits": (2, 10, 80),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RTDETRV2Detect": {
        "module": "kerasformers.models.rt_detr_v2",
        "model_cls": "RTDETRV2Detect",
        "model_type": "object_detection",
        "init_kwargs": {
            "backbone_hidden_sizes": (64, 128, 256, 512),
            "backbone_block_repeats": (2, 2, 2, 2),
            "backbone_layer_type": "basic",
            "encoder_in_channels": (128, 256, 512),
            "hidden_expansion": 0.5,
            "decoder_num_layers": 3,
            "image_size": 128,
            "num_queries": 10,
            "num_labels": 80,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": {
            "logits": (2, 10, 80),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RFDETRDetect": {
        "module": "kerasformers.models.rf_detr",
        "model_cls": "RFDETRDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "patch_size": 16,
            "num_windows": 2,
            "positional_encoding_size": 24,
            "resolution": 384,
            "dec_layers": 2,
            "num_queries": 10,
            "num_classes": 91,
            "image_size": 256,
        },
        "input_shape": (2, 256, 256, 3),
        "expected_output_shape": {
            "pred_logits": (2, 10, 91),
            "pred_boxes": (2, 10, 4),
        },
    },
    "RFDETRInstanceSegment": {
        "module": "kerasformers.models.rf_detr",
        "model_cls": "RFDETRInstanceSegment",
        "model_type": "instance_segmentation",
        "init_kwargs": {
            "patch_size": 16,
            "num_windows": 2,
            "positional_encoding_size": 24,
            "resolution": 384,
            "dec_layers": 2,
            "num_queries": 10,
            "num_classes": 91,
            "image_size": 256,
        },
        "input_shape": (2, 256, 256, 3),
        "expected_output_shape": {
            "pred_logits": (2, 10, 91),
            "pred_boxes": (2, 10, 4),
            "pred_masks": (2, 10, 64, 64),
        },
    },
    # ---------- Depth estimation ----------
    "DepthAnythingV1DepthEstimation": {
        "module": "kerasformers.models.depth_anything_v1",
        "model_cls": "DepthAnythingV1DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "image_size": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    "DepthAnythingV2DepthEstimation": {
        "module": "kerasformers.models.depth_anything_v2",
        "model_cls": "DepthAnythingV2DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "image_size": (42, 42, 3),
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    "DepthAnythingV2DepthEstimation_metric": {
        "module": "kerasformers.models.depth_anything_v2",
        "model_cls": "DepthAnythingV2DepthEstimation",
        "model_type": "depth_estimation",
        "init_kwargs": {
            "image_size": (42, 42, 3),
            "depth_estimation_type": "metric",
            "max_depth": 20.0,
        },
        "input_shape": (2, 42, 42, 3),
        "expected_output_shape": (2, 42, 42, 1),
    },
    # ---------- Semantic / universal segmentation ----------
    "DeepLabV3SemanticSegment": {
        "module": "kerasformers.models.deeplabv3",
        "model_cls": "DeepLabV3SemanticSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "backbone_variant": "ResNet50",
            "image_size": 64,
            "num_classes": 21,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": (2, 64, 64, 21),
    },
    "EoMTUniversalSegment": {
        "module": "kerasformers.models.eomt",
        "model_cls": "EoMTUniversalSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "hidden_dim": 384,
            "num_hidden_layers": 2,
            "num_heads": 6,
            "depths": 1,
            "layerscale_value": 1.0,
            "image_size": 64,
            "num_queries": 100,
            "num_labels": 133,
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": {
            "class_logits": (2, 100, 134),
            "mask_logits": (2, 100, 16, 16),
        },
    },
    "MaskFormerUniversalSegment": {
        "module": "kerasformers.models.maskformer",
        "model_cls": "MaskFormerUniversalSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "backbone_embed_dim": 32,
            "backbone_depths": (2, 2, 2, 2),
            "backbone_num_heads": (1, 2, 4, 8),
            "backbone_window_size": 7,
            "fpn_feature_size": 32,
            "mask_feature_size": 32,
            "decoder_d_model": 32,
            "decoder_num_layers": 2,
            "decoder_heads": 4,
            "decoder_ffn_dim": 64,
            "num_queries": 8,
            "num_classes": 10,
            "image_size": 224,
        },
        "input_shape": (2, 224, 224, 3),
        "expected_output_shape": {
            "class_queries_logits": (2, 8, 11),
            "masks_queries_logits": (2, 8, 56, 56),
        },
    },
    "Mask2FormerUniversalSegment": {
        "module": "kerasformers.models.mask2former",
        "model_cls": "Mask2FormerUniversalSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "backbone_embed_dim": 32,
            "backbone_depths": (2, 2, 2, 2),
            "backbone_num_heads": (1, 2, 4, 8),
            "backbone_window_size": 7,
            "hidden_dim": 32,
            "mask_feature_size": 32,
            "encoder_num_layers": 2,
            "encoder_ffn_dim": 64,
            "decoder_num_layers": 3,
            "decoder_ffn_dim": 64,
            "num_heads": 4,
            "num_queries": 8,
            "num_classes": 10,
            "image_size": 224,
        },
        "input_shape": (2, 224, 224, 3),
        "expected_output_shape": {
            "class_queries_logits": (2, 8, 11),
            "masks_queries_logits": (2, 8, 56, 56),
        },
    },
    "MobileViTSemanticSegment": {
        "module": "kerasformers.models.mobilevit",
        "model_cls": "MobileViTSemanticSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "initial_dims": 16,
            "head_dims": 320,
            "block_dims": [16, 24, 48, 64, 80],
            "expansion_ratio": [2.0, 2.0, 2.0, 2.0, 2.0],
            "attention_dims": [None, None, 64, 80, 96],
            "image_size": (128, 128, 3),
            "output_stride": 16,
            "num_classes": 21,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": (2, 8, 8, 21),
    },
    "MobileViTV2SemanticSegment": {
        "module": "kerasformers.models.mobilevitv2",
        "model_cls": "MobileViTV2SemanticSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "multiplier": 0.5,
            "image_size": (128, 128, 3),
            "output_stride": 16,
            "num_classes": 21,
        },
        "input_shape": (2, 128, 128, 3),
        "expected_output_shape": (2, 8, 8, 21),
    },
    "SegFormerSemanticSegment": {
        "module": "kerasformers.models.segformer",
        "model_cls": "SegFormerSemanticSegment",
        "model_type": "segmentation",
        "init_kwargs": {
            "image_size": 32,
            "num_classes": 150,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 32, 32, 150),
    },
    # ---------- Promptable segmentation ----------
    "SAMModel": {
        "module": "kerasformers.models.sam",
        "model_cls": "SAMModel",
        "model_type": "backbone",
        "init_kwargs": {
            "vision_hidden_size": 64,
            "vision_num_hidden_layers": 2,
            "vision_num_attention_heads": 2,
            "vision_mlp_dim": 128,
            "vision_global_attn_indexes": (1,),
            "image_size": (64, 64, 3),
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": None,
    },
    "SAMPromptableSegment": {
        "module": "kerasformers.models.sam",
        "model_cls": "SAMPromptableSegment",
        "model_type": "promptable_segmentation",
        "init_kwargs": {
            "vision_hidden_size": 64,
            "vision_num_hidden_layers": 2,
            "vision_num_attention_heads": 2,
            "vision_mlp_dim": 128,
            "vision_global_attn_indexes": (1,),
            "image_size": (64, 64, 3),
        },
        "input_factory": "sam_input",
        "input_factory_kwargs": {"image_size": 64},
        "expected_output_shape": {
            "pred_masks": None,
            "iou_scores": None,
        },
    },
    "SAM2Model": {
        "module": "kerasformers.models.sam2",
        "model_cls": "SAM2Model",
        "model_type": "backbone",
        "init_kwargs": {
            "hidden_dim": 32,
            "blocks_per_stage": (1, 1, 1, 1),
            "embed_dim_per_stage": (32, 64, 128, 256),
            "num_attention_heads_per_stage": (1, 1, 2, 2),
            "window_size_per_stage": (4, 2, 4, 2),
            "global_attention_blocks": (),
            "backbone_channel_list": (256, 128, 64, 32),
            "image_size": (64, 64, 3),
        },
        "input_shape": (2, 64, 64, 3),
        "expected_output_shape": None,
    },
    "SAM2PromptableSegment": {
        "module": "kerasformers.models.sam2",
        "model_cls": "SAM2PromptableSegment",
        "model_type": "promptable_segmentation",
        "init_kwargs": {
            "hidden_dim": 32,
            "blocks_per_stage": (1, 1, 1, 1),
            "embed_dim_per_stage": (32, 64, 128, 256),
            "num_attention_heads_per_stage": (1, 1, 2, 2),
            "window_size_per_stage": (4, 2, 4, 2),
            "global_attention_blocks": (),
            "backbone_channel_list": (256, 128, 64, 32),
            "image_size": (64, 64, 3),
        },
        "input_factory": "sam_input",
        "input_factory_kwargs": {"image_size": 64},
        "expected_output_shape": {
            "pred_masks": None,
            "iou_scores": None,
            "object_score_logits": None,
        },
    },
    # ---------- Vision-language (CLIP family) ----------
    "CLIPModel": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPModel",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "max_seq_len": 16,
            "vocab_size": 128,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": None,
    },
    "CLIPZeroShotClassify": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "max_seq_len": 16,
            "vocab_size": 128,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "CLIPImageClassify": {
        "module": "kerasformers.models.clip",
        "model_cls": "CLIPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_classes": 10,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (SigLIP family) ----------
    "SigLIPModel": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPModel",
        "model_type": "vlm",
        "init_kwargs": {
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocab_size": 128,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_seq_len": 16,
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": None,
    },
    "SigLIPZeroShotClassify": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocab_size": 128,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_seq_len": 16,
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "SigLIPImageClassify": {
        "module": "kerasformers.models.siglip",
        "model_cls": "SigLIPImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_classes": 10,
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (SigLIP 2 family) ----------
    "SigLIP2Model": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2Model",
        "model_type": "vlm",
        "init_kwargs": {
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocab_size": 256,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_seq_len": 16,
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": None,
    },
    "SigLIP2ZeroShotClassify": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2ZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
            "vocab_size": 256,
            "embed_dim": 64,
            "text_hidden_dim": 64,
            "text_num_layers": 2,
            "text_num_heads": 2,
            "text_intermediate_dim": 128,
            "max_seq_len": 16,
        },
        "input_factory": "siglip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "SigLIP2ImageClassify": {
        "module": "kerasformers.models.siglip2",
        "model_cls": "SigLIP2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_classes": 10,
            "image_size": (32, 32, 3),
            "patch_size": 16,
            "vision_hidden_dim": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "vision_intermediate_dim": 128,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Vision-language (MetaCLIP 2) ----------
    "MetaClip2Model": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2Model",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "max_seq_len": 16,
            "vocab_size": 256,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": None,
    },
    "MetaClip2ZeroShotClassify": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2ZeroShotClassify",
        "model_type": "vlm",
        "init_kwargs": {
            "embed_dim": 32,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
            "max_seq_len": 16,
            "vocab_size": 256,
            "transformer_width": 32,
            "transformer_heads": 2,
            "transformer_layers": 2,
        },
        "input_factory": "clip_input",
        "input_factory_kwargs": {"image_size": 32, "max_seq_len": 16},
        "expected_output_shape": {
            "image_logits": (2, 2),
            "text_logits": (2, 2),
        },
    },
    "MetaClip2ImageClassify": {
        "module": "kerasformers.models.metaclip2",
        "model_cls": "MetaClip2ImageClassify",
        "model_type": "classification",
        "init_kwargs": {
            "num_classes": 10,
            "image_size": (32, 32, 3),
            "vision_layers": 2,
            "vision_width": 64,
            "vision_patch_size": 16,
        },
        "input_shape": (2, 32, 32, 3),
        "expected_output_shape": (2, 10),
    },
    # ---------- Audio (Whisper) ----------
    "WhisperModel": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperModel",
        "model_type": "audio",
        "init_kwargs": {
            "hidden_dim": 64,
            "encoder_num_layers": 1,
            "decoder_num_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "max_target_positions": 10,
            "vocab_size": 128,
        },
        "input_factory": "whisper_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "mel_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 20, 64),
            "logits": (2, 5, 128),
        },
    },
    "WhisperSpeechToText": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperSpeechToText",
        "model_type": "audio",
        "init_kwargs": {
            "hidden_dim": 64,
            "encoder_num_layers": 1,
            "decoder_num_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "max_target_positions": 10,
            "vocab_size": 128,
        },
        "input_factory": "whisper_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "mel_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 20, 64),
            "logits": (2, 5, 128),
        },
    },
    "WhisperAudioClassify": {
        "module": "kerasformers.models.whisper",
        "model_cls": "WhisperAudioClassify",
        "model_type": "audio",
        "init_kwargs": {
            "hidden_dim": 64,
            "encoder_num_layers": 1,
            "encoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "num_mel_bins": 80,
            "max_source_positions": 20,
            "num_classes": 10,
            "classifier_proj_size": 32,
        },
        "input_factory": "whisper_audio_input",
        "input_factory_kwargs": {"num_mel_bins": 80, "mel_length": 40},
        "expected_output_shape": (2, 10),
    },
    # ---------- Audio (Speech2Text) ----------
    "Speech2TextModel": {
        "module": "kerasformers.models.speech2text",
        "model_cls": "Speech2TextModel",
        "model_type": "audio",
        "init_kwargs": {
            "hidden_dim": 64,
            "encoder_num_layers": 1,
            "decoder_num_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "vocab_size": 128,
            "num_mel_bins": 80,
            "max_source_positions": 50,
            "max_target_positions": 10,
            "conv_channels": 64,
            "conv_kernel_sizes": (5, 5),
            "num_conv_layers": 2,
        },
        "input_factory": "speech2text_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "feat_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 10, 64),
            "logits": (2, 5, 128),
        },
    },
    "Speech2TextSpeechToText": {
        "module": "kerasformers.models.speech2text",
        "model_cls": "Speech2TextSpeechToText",
        "model_type": "audio",
        "init_kwargs": {
            "hidden_dim": 64,
            "encoder_num_layers": 1,
            "decoder_num_layers": 1,
            "encoder_attention_heads": 2,
            "decoder_attention_heads": 2,
            "encoder_ffn_dim": 128,
            "decoder_ffn_dim": 128,
            "vocab_size": 128,
            "num_mel_bins": 80,
            "max_source_positions": 50,
            "max_target_positions": 10,
            "conv_channels": 64,
            "conv_kernel_sizes": (5, 5),
            "num_conv_layers": 2,
        },
        "input_factory": "speech2text_input",
        "input_factory_kwargs": {
            "num_mel_bins": 80,
            "feat_length": 40,
            "decoder_seq_len": 5,
        },
        "expected_output_shape": {
            "encoder_hidden_states": (2, 10, 64),
            "logits": (2, 5, 128),
        },
    },
    "OwlViTDetect": {
        "module": "kerasformers.models.owlvit",
        "model_cls": "OwlViTDetect",
        "model_type": "object_detection",
        "init_kwargs": {
            "vision_image_size": 64,
            "vision_patch_size": 16,
            "vision_hidden_dim": 32,
            "vision_intermediate_size": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "text_hidden_dim": 16,
            "text_intermediate_size": 32,
            "text_num_heads": 2,
            "projection_dim": 16,
            "image_size": 64,
        },
        "input_factory": "owlvit_input",
        "input_factory_kwargs": {
            "image_size": 64,
            "max_seq_len": 16,
            "num_queries": 2,
        },
        "expected_output_shape": {
            "logits": (2, 16, 2),
            "pred_boxes": (2, 16, 4),
        },
    },
    "Owlv2Detect": {
        "module": "kerasformers.models.owlv2",
        "model_cls": "Owlv2Detect",
        "model_type": "object_detection",
        "init_kwargs": {
            "vision_image_size": 64,
            "vision_patch_size": 16,
            "vision_hidden_dim": 32,
            "vision_intermediate_size": 64,
            "vision_num_layers": 2,
            "vision_num_heads": 2,
            "text_hidden_dim": 16,
            "text_intermediate_size": 32,
            "text_num_heads": 2,
            "projection_dim": 16,
            "image_size": 64,
        },
        "input_factory": "owlvit_input",
        "input_factory_kwargs": {
            "image_size": 64,
            "max_seq_len": 16,
            "num_queries": 2,
        },
        "expected_output_shape": {
            "logits": (2, 16, 2),
            "objectness_logits": (2, 16),
            "pred_boxes": (2, 16, 4),
        },
    },
    # ---- Multimodal LLMs (Qwen-VL): XModel -> features, XGenerate -> logits ----
    "Qwen2VLModel": {
        "module": "kerasformers.models.qwen2_vl",
        "model_cls": "Qwen2VLModel",
        "model_type": "vlm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "mrope_section": (2, 3, 3),
            "tie_embeddings": True,
            "vision_depth": 2,
            "vision_embed_dim": 32,
            "vision_num_heads": 4,
            "patch_size": 14,
            "spatial_merge_size": 2,
            "image_token_id": 4,
        },
        "input_factory": "qwen_vl_input",
        "input_factory_kwargs": {
            "grid": (1, 4, 4),
            "patch_dim": 1176,
            "image_token_id": 4,
        },
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    "Qwen2_5_VLModel": {
        "module": "kerasformers.models.qwen2_5_vl",
        "model_cls": "Qwen2_5_VLModel",
        "model_type": "vlm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "mrope_section": (2, 3, 3),
            "tie_embeddings": True,
            "vision_depth": 4,
            "vision_hidden_size": 32,
            "vision_intermediate_size": 64,
            "vision_num_heads": 4,
            "vision_out_hidden_size": 64,
            "window_size": 56,
            "fullatt_block_indexes": (1, 3),
            "tokens_per_second": 2,
            "patch_size": 14,
            "spatial_merge_size": 2,
            "image_token_id": 4,
        },
        "input_factory": "qwen_vl_input",
        "input_factory_kwargs": {
            "grid": (1, 4, 4),
            "patch_dim": 1176,
            "image_token_id": 4,
        },
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    "Qwen3VLModel": {
        "module": "kerasformers.models.qwen3_vl",
        "model_cls": "Qwen3VLModel",
        "model_type": "vlm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "head_dim": 16,
            "mrope_section": (2, 2, 2),
            "rope_theta": 5000000.0,
            "tie_embeddings": True,
            "vision_depth": 4,
            "vision_hidden_size": 32,
            "vision_intermediate_size": 64,
            "vision_num_heads": 4,
            "vision_out_hidden_size": 64,
            "num_position_embeddings": 64,
            "deepstack_visual_indexes": (1, 3),
            "patch_size": 16,
            "spatial_merge_size": 2,
            "image_token_id": 4,
        },
        "input_factory": "qwen_vl_input",
        "input_factory_kwargs": {
            "grid": (1, 4, 4),
            "patch_dim": 1536,
            "image_token_id": 4,
        },
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    # ---- Text encoders (BERT) ----
    "BertModel": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertModel",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {
            "last_hidden_state": (2, 16, 32),
            "pooler_output": (2, 32),
        },
    },
    "BertMaskedLM": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertMaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "BertSequenceClassify": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertSequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
            "num_classes": 4,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "BertTokenClassify": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertTokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
            "num_classes": 5,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "BertNextSentencePredict": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertNextSentencePredict",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 2),
    },
    "BertQnA": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertQnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    "BertMultipleChoice": {
        "module": "kerasformers.models.bert",
        "model_cls": "BertMultipleChoice",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 2,
            "num_choices": 3,
        },
        "input_factory": "bert_multiple_choice_input",
        "input_factory_kwargs": {"num_choices": 3, "seq_len": 16},
        "expected_output_shape": (2, 3),
    },
    # ---- Text encoders (RoBERTa) ----
    "RobertaModel": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaModel",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {
            "last_hidden_state": (2, 16, 32),
            "pooler_output": (2, 32),
        },
    },
    "RobertaMaskedLM": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaMaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "RobertaSequenceClassify": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaSequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_classes": 4,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "RobertaTokenClassify": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaTokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_classes": 5,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "RobertaQnA": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaQnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    "RobertaMultipleChoice": {
        "module": "kerasformers.models.roberta",
        "model_cls": "RobertaMultipleChoice",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_choices": 3,
        },
        "input_factory": "roberta_multiple_choice_input",
        "input_factory_kwargs": {"num_choices": 3, "seq_len": 16},
        "expected_output_shape": (2, 3),
    },
    # ---- Text encoders (XLM-RoBERTa) ----
    "XLMRobertaModel": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaModel",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {
            "last_hidden_state": (2, 16, 32),
            "pooler_output": (2, 32),
        },
    },
    "XLMRobertaMaskedLM": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaMaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "XLMRobertaSequenceClassify": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaSequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_classes": 4,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "XLMRobertaTokenClassify": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaTokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_classes": 5,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "XLMRobertaQnA": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaQnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
        },
        "input_factory": "roberta_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    "XLMRobertaMultipleChoice": {
        "module": "kerasformers.models.xlm_roberta",
        "model_cls": "XLMRobertaMultipleChoice",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "type_vocab_size": 1,
            "num_choices": 3,
        },
        "input_factory": "roberta_multiple_choice_input",
        "input_factory_kwargs": {"num_choices": 3, "seq_len": 16},
        "expected_output_shape": (2, 3),
    },
    # ---- Text encoders (DeBERTa v1) ----
    "DebertaModel": {
        "module": "kerasformers.models.deberta",
        "model_cls": "DebertaModel",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"last_hidden_state": (2, 16, 32)},
    },
    "DebertaMaskedLM": {
        "module": "kerasformers.models.deberta",
        "model_cls": "DebertaMaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "DebertaSequenceClassify": {
        "module": "kerasformers.models.deberta",
        "model_cls": "DebertaSequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "num_classes": 4,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "DebertaTokenClassify": {
        "module": "kerasformers.models.deberta",
        "model_cls": "DebertaTokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "num_classes": 5,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "DebertaQnA": {
        "module": "kerasformers.models.deberta",
        "model_cls": "DebertaQnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    # ---- Text encoders (DeBERTa v2) ----
    "DebertaV2Model": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2Model",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"last_hidden_state": (2, 16, 32)},
    },
    "DebertaV2MaskedLM": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2MaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "DebertaV2SequenceClassify": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2SequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
            "num_classes": 4,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "DebertaV2TokenClassify": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2TokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
            "num_classes": 5,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "DebertaV2QnA": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2QnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    "DebertaV2MultipleChoice": {
        "module": "kerasformers.models.deberta_v2",
        "model_cls": "DebertaV2MultipleChoice",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 3,
            "num_choices": 3,
        },
        "input_factory": "bert_multiple_choice_input",
        "input_factory_kwargs": {"num_choices": 3, "seq_len": 16},
        "expected_output_shape": (2, 3),
    },
    # ---- Text encoders (DeBERTa v3) ----
    "DebertaV3Model": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3Model",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"last_hidden_state": (2, 16, 32)},
    },
    "DebertaV3MaskedLM": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3MaskedLM",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 128),
    },
    "DebertaV3SequenceClassify": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3SequenceClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
            "num_classes": 4,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 4),
    },
    "DebertaV3TokenClassify": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3TokenClassify",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
            "num_classes": 5,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": (2, 16, 5),
    },
    "DebertaV3QnA": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3QnA",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
        },
        "input_factory": "bert_input",
        "input_factory_kwargs": {"seq_len": 16},
        "expected_output_shape": {"start_logits": (2, 16), "end_logits": (2, 16)},
    },
    "DebertaV3MultipleChoice": {
        "module": "kerasformers.models.deberta_v3",
        "model_cls": "DebertaV3MultipleChoice",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 32,
            "num_layers": 2,
            "num_heads": 2,
            "mlp_dim": 64,
            "max_position_embeddings": 64,
            "max_relative_positions": 64,
            "position_buckets": 32,
            "norm_rel_ebd": True,
            "conv_kernel_size": 0,
            "num_choices": 3,
        },
        "input_factory": "bert_multiple_choice_input",
        "input_factory_kwargs": {"num_choices": 3, "seq_len": 16},
        "expected_output_shape": (2, 3),
    },
    # ---- Text LLMs (Qwen): XModel -> features, XGenerate -> logits ----
    "Qwen2Model": {
        "module": "kerasformers.models.qwen2",
        "model_cls": "Qwen2Model",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "head_dim": 16,
            "tie_embeddings": True,
        },
        "input_factory": "qwen_text_input",
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    "Qwen3Model": {
        "module": "kerasformers.models.qwen3",
        "model_cls": "Qwen3Model",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "head_dim": 16,
            "tie_embeddings": True,
        },
        "input_factory": "qwen_text_input",
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    "Qwen3_5Model": {
        "module": "kerasformers.models.qwen3_5",
        "model_cls": "Qwen3_5Model",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "mlp_dim": 128,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "head_dim": 16,
            "partial_rotary_factor": 0.5,
            "tie_embeddings": True,
            "full_attention_interval": 2,
            "linear_conv_kernel_dim": 4,
            "linear_key_head_dim": 8,
            "linear_value_head_dim": 8,
            "linear_num_key_heads": 2,
            "linear_num_value_heads": 2,
        },
        "input_factory": "qwen_text_input",
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
    "GptOssModel": {
        "module": "kerasformers.models.gpt_oss",
        "model_cls": "GptOssModel",
        "model_type": "llm",
        "init_kwargs": {
            "vocab_size": 128,
            "embed_dim": 64,
            "intermediate_size": 32,
            "num_layers": 2,
            "num_heads": 4,
            "num_kv_heads": 2,
            "head_dim": 16,
            "num_experts": 8,
            "num_experts_per_tok": 2,
            "sliding_window": 4,
        },
        "input_factory": "qwen_text_input",
        "expected_output_shape": {"last_hidden_state": (2, 6, 64)},
    },
}


# The Qwen-VL `*Generate` classes share their base model's config + input but
# add an LM head, so derive their test entries (logits output) from the bases.
for _base in ("Qwen2VLModel", "Qwen2_5_VLModel", "Qwen3VLModel"):
    _gen = _base.replace("VLModel", "VLGenerate")
    _entry = dict(MODEL_TEST_CONFIGS[_base])
    _entry["model_cls"] = _gen
    _entry["expected_output_shape"] = {"logits": (2, 6, 128)}
    MODEL_TEST_CONFIGS[_gen] = _entry


# Same for the text `*Generate` classes (Qwen2/Qwen3/Qwen3.5).
for _base in ("Qwen2Model", "Qwen3Model", "Qwen3_5Model", "GptOssModel"):
    _gen = _base.replace("Model", "Generate")
    _entry = dict(MODEL_TEST_CONFIGS[_base])
    _entry["model_cls"] = _gen
    _entry["expected_output_shape"] = {"logits": (2, 6, 128)}
    MODEL_TEST_CONFIGS[_gen] = _entry


def get_all_model_ids():
    return list(MODEL_TEST_CONFIGS.keys())


def get_models_by_type(model_type):
    return {
        k: v for k, v in MODEL_TEST_CONFIGS.items() if v["model_type"] == model_type
    }


def import_model_class(config):
    import importlib

    module = importlib.import_module(config["module"])
    return getattr(module, config["model_cls"])


def create_test_input(config, batch_size=2):
    from tests.fixtures import dummy_inputs

    if "input_factory" in config:
        factory_fn = getattr(dummy_inputs, config["input_factory"])
        factory_kwargs = config.get("input_factory_kwargs", {})
        return factory_fn(batch_size=batch_size, **factory_kwargs)

    from keras import ops

    shape = config["input_shape"]
    return ops.ones(shape)
