GPT_OSS_CONFIG = {
    "gpt-oss-20b": {
        "vocab_size": 201088,
        "embed_dim": 2880,
        "intermediate_size": 2880,
        "num_layers": 24,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 64,
        "num_experts": 32,
        "num_experts_per_tok": 4,
        "sliding_window": 128,
        "norm_eps": 1e-5,
        "rope_theta": 150000.0,
        "rope_factor": 32.0,
        "rope_beta_fast": 32.0,
        "rope_beta_slow": 1.0,
        "rope_truncate": False,
        "rope_original_max_pos": 4096,
        "attention_bias": True,
        "tie_embeddings": False,
    },
    "gpt-oss-120b": {
        "vocab_size": 201088,
        "embed_dim": 2880,
        "intermediate_size": 2880,
        "num_layers": 36,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 64,
        "num_experts": 128,
        "num_experts_per_tok": 4,
        "sliding_window": 128,
        "norm_eps": 1e-5,
        "rope_theta": 150000.0,
        "rope_factor": 32.0,
        "rope_beta_fast": 32.0,
        "rope_beta_slow": 1.0,
        "rope_truncate": False,
        "rope_original_max_pos": 4096,
        "attention_bias": True,
        "tie_embeddings": False,
    },
}

GPT_OSS_WEIGHTS = {
    "gpt-oss-20b": {"hf_id": "openai/gpt-oss-20b", "gated": False, "safetensors": True},
    "gpt-oss-120b": {
        "hf_id": "openai/gpt-oss-120b",
        "gated": False,
        "safetensors": True,
    },
}
