GRANITE_SPEECH_CONFIG = {
    "granite_speech_3_3_2b": {
        "vocab_size": 49160,
        "embed_dim": 2048,
        "mlp_dim": 8192,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "norm_eps": 1e-5,
        "rope_theta": 10000000.0,
        "embedding_multiplier": 12.0,
        "residual_multiplier": 0.22,
        "attention_multiplier": 0.015625,
        "logits_scaling": 8.0,
        "tie_embeddings": True,
        "eos_token_id": 0,
        "audio_token_id": 49159,
        "downsample_rate": 5,
        "window_size": 15,
        "has_lora_adapter": True,
        "lora_rank": 64,
        "lora_alpha": 32,
        "encoder_input_dim": 160,
        "encoder_num_layers": 16,
        "encoder_hidden_dim": 1024,
        "encoder_feedforward_mult": 4,
        "encoder_num_heads": 8,
        "encoder_dim_head": 128,
        "encoder_output_dim": 256,
        "encoder_context_size": 200,
        "encoder_max_pos_emb": 512,
        "encoder_conv_kernel_size": 15,
        "encoder_conv_expansion_factor": 2,
        "projector_dim": 1024,
        "projector_num_layers": 2,
        "projector_num_heads": 16,
        "projector_intermediate_size": 4096,
        "projector_cross_attention_frequency": 1,
        "projector_layer_norm_eps": 1e-12,
        "cat_hidden_layers": None,
    },
    "granite_speech_3_3_8b": {
        "vocab_size": 49160,
        "embed_dim": 4096,
        "mlp_dim": 12800,
        "num_layers": 40,
        "num_heads": 32,
        "num_kv_heads": 8,
        "norm_eps": 1e-5,
        "rope_theta": 10000000.0,
        "embedding_multiplier": 12.0,
        "residual_multiplier": 0.22,
        "attention_multiplier": 0.0078125,
        "logits_scaling": 16.0,
        "tie_embeddings": True,
        "eos_token_id": 0,
        "audio_token_id": 49159,
        "downsample_rate": 5,
        "window_size": 15,
        "has_lora_adapter": True,
        "lora_rank": 64,
        "lora_alpha": 32,
        "encoder_input_dim": 160,
        "encoder_num_layers": 16,
        "encoder_hidden_dim": 1024,
        "encoder_feedforward_mult": 4,
        "encoder_num_heads": 8,
        "encoder_dim_head": 128,
        "encoder_output_dim": 256,
        "encoder_context_size": 200,
        "encoder_max_pos_emb": 512,
        "encoder_conv_kernel_size": 15,
        "encoder_conv_expansion_factor": 2,
        "projector_dim": 1024,
        "projector_num_layers": 2,
        "projector_num_heads": 16,
        "projector_intermediate_size": 4096,
        "projector_cross_attention_frequency": 1,
        "projector_layer_norm_eps": 1e-12,
        "cat_hidden_layers": None,
    },
    "granite_speech_4_1_2b": {
        "vocab_size": 100353,
        "embed_dim": 2048,
        "mlp_dim": 4096,
        "num_layers": 40,
        "num_heads": 16,
        "num_kv_heads": 4,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "embedding_multiplier": 12.0,
        "residual_multiplier": 0.22,
        "attention_multiplier": 0.0078125,
        "logits_scaling": 8.0,
        "tie_embeddings": False,
        "eos_token_id": 100257,
        "audio_token_id": 100352,
        "downsample_rate": 5,
        "window_size": 15,
        "has_lora_adapter": False,
        "lora_rank": 64,
        "lora_alpha": 32,
        "encoder_input_dim": 160,
        "encoder_num_layers": 16,
        "encoder_hidden_dim": 1024,
        "encoder_feedforward_mult": 4,
        "encoder_num_heads": 8,
        "encoder_dim_head": 128,
        "encoder_output_dim": 348,
        "encoder_context_size": 200,
        "encoder_max_pos_emb": 512,
        "encoder_conv_kernel_size": 15,
        "encoder_conv_expansion_factor": 2,
        "projector_dim": 1024,
        "projector_num_layers": 2,
        "projector_num_heads": 16,
        "projector_intermediate_size": 4096,
        "projector_cross_attention_frequency": 1,
        "projector_layer_norm_eps": 1e-12,
        "cat_hidden_layers": None,
    },
    "granite_4_0_1b_speech": {
        "vocab_size": 100353,
        "embed_dim": 2048,
        "mlp_dim": 4096,
        "num_layers": 40,
        "num_heads": 16,
        "num_kv_heads": 4,
        "norm_eps": 1e-5,
        "rope_theta": 10000.0,
        "embedding_multiplier": 12.0,
        "residual_multiplier": 0.22,
        "attention_multiplier": 0.0078125,
        "logits_scaling": 8.0,
        "tie_embeddings": False,
        "eos_token_id": 100257,
        "audio_token_id": 100352,
        "downsample_rate": 5,
        "window_size": 15,
        "has_lora_adapter": False,
        "lora_rank": 64,
        "lora_alpha": 32,
        "encoder_input_dim": 160,
        "encoder_num_layers": 16,
        "encoder_hidden_dim": 1024,
        "encoder_feedforward_mult": 4,
        "encoder_num_heads": 8,
        "encoder_dim_head": 128,
        "encoder_output_dim": 348,
        "encoder_context_size": 200,
        "encoder_max_pos_emb": 512,
        "encoder_conv_kernel_size": 15,
        "encoder_conv_expansion_factor": 2,
        "projector_dim": 1024,
        "projector_num_layers": 2,
        "projector_num_heads": 16,
        "projector_intermediate_size": 4096,
        "projector_cross_attention_frequency": 1,
        "projector_layer_norm_eps": 1e-12,
        "cat_hidden_layers": None,
    },
}


GRANITE_SPEECH_WEIGHTS_URLS = {
    "granite_speech_3_3_2b": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_3_3_2b.weights.json",
    },
    "granite_speech_3_3_8b": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_3_3_8b.weights.json",
    },
    "granite_speech_4_1_2b": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_4_1_2b.weights.json",
    },
    "granite_4_0_1b_speech": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_4_0_1b_speech.weights.json",
    },
}

GRANITE_SPEECH_TOKENIZER_URLS = {
    "granite_speech_3_3_2b": {
        "tokenizer_json": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_3_3_2b_tokenizer.json"
    },
    "granite_speech_3_3_8b": {
        "tokenizer_json": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_3_3_8b_tokenizer.json"
    },
    "granite_speech_4_1_2b": {
        "tokenizer_json": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_speech_4_1_2b_tokenizer.json"
    },
    "granite_4_0_1b_speech": {
        "tokenizer_json": "https://github.com/IMvision12/KerasFormers/releases/download/granite/granite_4_0_1b_speech_tokenizer.json"
    },
}
