METACLIP2_CONFIG = {
    "metaclip2_worldwide_s16_224": {
        "embed_dim": 384,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 384,
        "vision_patch_size": 16,
        "vision_num_heads": 6,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 384,
        "text_num_heads": 6,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_s16_384": {
        "embed_dim": 384,
        "image_size": 384,
        "vision_num_layers": 12,
        "vision_hidden_dim": 384,
        "vision_patch_size": 16,
        "vision_num_heads": 6,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 384,
        "text_num_heads": 6,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_m16_224": {
        "embed_dim": 512,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 512,
        "vision_patch_size": 16,
        "vision_num_heads": 8,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_m16_384": {
        "embed_dim": 512,
        "image_size": 384,
        "vision_num_layers": 12,
        "vision_hidden_dim": 512,
        "vision_patch_size": 16,
        "vision_num_heads": 8,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_b16_224": {
        "embed_dim": 512,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 768,
        "vision_patch_size": 16,
        "vision_num_heads": 12,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_b16_384": {
        "embed_dim": 512,
        "image_size": 384,
        "vision_num_layers": 12,
        "vision_hidden_dim": 768,
        "vision_patch_size": 16,
        "vision_num_heads": 12,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_b32_224": {
        "embed_dim": 512,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 768,
        "vision_patch_size": 32,
        "vision_num_heads": 12,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_b32_384": {
        "embed_dim": 512,
        "image_size": 384,
        "vision_num_layers": 12,
        "vision_hidden_dim": 768,
        "vision_patch_size": 32,
        "vision_num_heads": 12,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_l14_224": {
        "embed_dim": 768,
        "image_size": 224,
        "vision_num_layers": 24,
        "vision_hidden_dim": 1024,
        "vision_patch_size": 14,
        "vision_num_heads": 16,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 768,
        "text_num_heads": 12,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_huge_quickgelu": {
        "embed_dim": 1024,
        "image_size": 224,
        "vision_num_layers": 32,
        "vision_hidden_dim": 1280,
        "vision_patch_size": 14,
        "vision_num_heads": 16,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 1024,
        "text_num_heads": 16,
        "text_num_layers": 24,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "quick_gelu",
    },
    "metaclip2_worldwide_huge_378": {
        "embed_dim": 1024,
        "image_size": 378,
        "vision_num_layers": 32,
        "vision_hidden_dim": 1280,
        "vision_patch_size": 14,
        "vision_num_heads": 16,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 1024,
        "text_num_heads": 16,
        "text_num_layers": 24,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_giant_224": {
        "embed_dim": 1280,
        "image_size": 224,
        "vision_num_layers": 48,
        "vision_hidden_dim": 1664,
        "vision_patch_size": 14,
        "vision_num_heads": 16,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 1280,
        "text_num_heads": 20,
        "text_num_layers": 32,
        "vision_mlp_ratio": 8192 / 1664,
        "text_mlp_ratio": 5120 / 1280,
        "hidden_act": "gelu",
    },
    "metaclip2_worldwide_giant_378": {
        "embed_dim": 1280,
        "image_size": 378,
        "vision_num_layers": 48,
        "vision_hidden_dim": 1664,
        "vision_patch_size": 14,
        "vision_num_heads": 16,
        "max_seq_len": 77,
        "vocab_size": 901629,
        "text_hidden_dim": 1280,
        "text_num_heads": 20,
        "text_num_layers": 32,
        "vision_mlp_ratio": 8192 / 1664,
        "text_mlp_ratio": 5120 / 1280,
        "hidden_act": "gelu",
    },
    "metaclip2_mt5_worldwide_s16_224": {
        "embed_dim": 384,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 384,
        "vision_patch_size": 16,
        "vision_num_heads": 6,
        "max_seq_len": 77,
        "vocab_size": 250000,
        "text_hidden_dim": 384,
        "text_num_heads": 6,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
        "eos_token_id": 1,
    },
    "metaclip2_mt5_worldwide_m16_224": {
        "embed_dim": 512,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 512,
        "vision_patch_size": 16,
        "vision_num_heads": 8,
        "max_seq_len": 77,
        "vocab_size": 250000,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
        "eos_token_id": 1,
    },
    "metaclip2_mt5_worldwide_b32_224": {
        "embed_dim": 512,
        "image_size": 224,
        "vision_num_layers": 12,
        "vision_hidden_dim": 768,
        "vision_patch_size": 32,
        "vision_num_heads": 12,
        "max_seq_len": 77,
        "vocab_size": 250000,
        "text_hidden_dim": 512,
        "text_num_heads": 8,
        "text_num_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "gelu",
        "eos_token_id": 1,
    },
}

METACLIP2_WEIGHTS = {
    "metaclip2_worldwide_s16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_s16_224.weights.h5",
    },
    "metaclip2_worldwide_s16_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_s16_384.weights.h5",
    },
    "metaclip2_worldwide_m16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_m16_224.weights.json",
    },
    "metaclip2_worldwide_m16_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_m16_384.weights.json",
    },
    "metaclip2_worldwide_b16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_b16_224.weights.json",
    },
    "metaclip2_worldwide_b16_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_b16_384.weights.json",
    },
    "metaclip2_worldwide_b32_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_b32_224.weights.json",
    },
    "metaclip2_worldwide_b32_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_worldwide_b32_384.weights.json",
    },
    # L14/Huge/Giant: a single token-embedding tensor exceeds GitHub's 2 GiB
    # asset limit, so these are converted from the source checkpoints on the fly via
    # ``load_and_convert_from_hf`` (cached under ~/.cache/kerasformers/).
    # Used through the normal variant name — no "hf:" prefix needed.
    "metaclip2_worldwide_l14_224": {
        "hf_id": "facebook/metaclip-2-worldwide-l14",
    },
    "metaclip2_worldwide_huge_quickgelu": {
        "hf_id": "facebook/metaclip-2-worldwide-huge-quickgelu",
    },
    "metaclip2_worldwide_huge_378": {
        "hf_id": "facebook/metaclip-2-worldwide-huge-378",
    },
    "metaclip2_worldwide_giant_224": {
        "hf_id": "facebook/metaclip-2-worldwide-giant",
    },
    "metaclip2_worldwide_giant_378": {
        "hf_id": "facebook/metaclip-2-worldwide-giant-378",
    },
    "metaclip2_mt5_worldwide_s16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_mt5_worldwide_s16_224.weights.h5",
    },
    "metaclip2_mt5_worldwide_m16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_mt5_worldwide_m16_224.weights.h5",
    },
    "metaclip2_mt5_worldwide_b32_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/metaclip2/metaclip2_mt5_worldwide_b32_224.weights.h5",
    },
}
