# Architecture configs from the official params.json (HF-schema equivalents).
# The official mistralai/Mistral-Large-3-* repos ship mistral-native
# consolidated shards (no HF-format config.json / model safetensors), so no
# weight entries are registered: build with load_weights=False, or load an
# HF-format export via from_weights("hf:<repo>").
MISTRAL4_CONFIG = {
    "mistral-large-3-675b-base": {
        "vocab_size": 131072,
        "embed_dim": 7168,
        "mlp_dim_dense": 16384,
        "moe_mlp_dim": 4096,
        "num_layers": 61,
        "num_heads": 128,
        "num_experts": 128,
        "num_experts_per_tok": 4,
        "n_shared_experts": 1,
        "n_group": 1,
        "topk_group": 1,
        "norm_topk_prob": True,
        "routed_scaling_factor": 1.0,
        "first_k_dense_replace": 3,
        "q_lora_rank": 1536,
        "kv_lora_rank": 512,
        "qk_nope_head_dim": 128,
        "qk_rope_head_dim": 64,
        "v_head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 10000.0,
        "rope_interleave": True,
        "llama4_beta": 0.1,
        "llama4_original_max": 8192,
        "tie_embeddings": False,
    },
    "mistral-large-3-675b-instruct": {
        "vocab_size": 131072,
        "embed_dim": 7168,
        "mlp_dim_dense": 16384,
        "moe_mlp_dim": 4096,
        "num_layers": 61,
        "num_heads": 128,
        "num_experts": 128,
        "num_experts_per_tok": 4,
        "n_shared_experts": 1,
        "n_group": 1,
        "topk_group": 1,
        "norm_topk_prob": True,
        "routed_scaling_factor": 1.0,
        "first_k_dense_replace": 3,
        "q_lora_rank": 1536,
        "kv_lora_rank": 512,
        "qk_nope_head_dim": 128,
        "qk_rope_head_dim": 64,
        "v_head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 10000.0,
        "rope_interleave": True,
        "llama4_beta": 0.1,
        "llama4_original_max": 8192,
        "tie_embeddings": False,
    },
}

MISTRAL4_WEIGHTS_URLS = {}
