MASKFORMER_CONFIG = {
    "maskformer-swin-tiny-ade": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 6, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "fpn_feature_size": 256,
        "mask_feature_size": 256,
        "decoder_d_model": 256,
        "decoder_num_layers": 6,
        "decoder_heads": 8,
        "decoder_ffn_dim": 2048,
        "num_queries": 100,
        "num_classes": 150,
        "image_size": 512,
    },
    "maskformer-swin-tiny-coco": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 6, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "fpn_feature_size": 256,
        "mask_feature_size": 256,
        "decoder_d_model": 256,
        "decoder_num_layers": 6,
        "decoder_heads": 8,
        "decoder_ffn_dim": 2048,
        "num_queries": 100,
        "num_classes": 133,
        "image_size": 384,
    },
    "maskformer-swin-small-coco": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "fpn_feature_size": 256,
        "mask_feature_size": 256,
        "decoder_d_model": 256,
        "decoder_num_layers": 6,
        "decoder_heads": 8,
        "decoder_ffn_dim": 2048,
        "num_queries": 100,
        "num_classes": 133,
        "image_size": 384,
    },
    "maskformer-swin-base-ade": {
        "backbone_embed_dim": 128,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (4, 8, 16, 32),
        "backbone_window_size": 12,
        "fpn_feature_size": 256,
        "mask_feature_size": 256,
        "decoder_d_model": 256,
        "decoder_num_layers": 6,
        "decoder_heads": 8,
        "decoder_ffn_dim": 2048,
        "num_queries": 100,
        "num_classes": 150,
        "image_size": 512,
    },
    "maskformer-swin-base-coco": {
        "backbone_embed_dim": 128,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (4, 8, 16, 32),
        "backbone_window_size": 12,
        "fpn_feature_size": 256,
        "mask_feature_size": 256,
        "decoder_d_model": 256,
        "decoder_num_layers": 6,
        "decoder_heads": 8,
        "decoder_ffn_dim": 2048,
        "num_queries": 100,
        "num_classes": 133,
        "image_size": 384,
    },
}

MASKFORMER_WEIGHTS_URLS = {
    "maskformer-swin-tiny-ade": {
        "url": "https://huggingface.co/kerasformers/maskformer-swin-tiny-ade",
    },
    "maskformer-swin-tiny-coco": {
        "url": "https://huggingface.co/kerasformers/maskformer-swin-tiny-coco",
    },
    "maskformer-swin-small-coco": {
        "url": "https://huggingface.co/kerasformers/maskformer-swin-small-coco",
    },
    "maskformer-swin-base-ade": {
        "url": "https://huggingface.co/kerasformers/maskformer-swin-base-ade",
    },
    "maskformer-swin-base-coco": {
        "url": "https://huggingface.co/kerasformers/maskformer-swin-base-coco",
    },
}
