QWEN3_CONFIG = {
    "qwen3-0.6b": {
        "vocab_size": 151936,
        "embed_dim": 1024,
        "mlp_dim": 3072,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-0.6b-base": {
        "vocab_size": 151936,
        "embed_dim": 1024,
        "mlp_dim": 3072,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-1.7b": {
        "vocab_size": 151936,
        "embed_dim": 2048,
        "mlp_dim": 6144,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-1.7b-base": {
        "vocab_size": 151936,
        "embed_dim": 2048,
        "mlp_dim": 6144,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-4b": {
        "vocab_size": 151936,
        "embed_dim": 2560,
        "mlp_dim": 9728,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-4b-base": {
        "vocab_size": 151936,
        "embed_dim": 2560,
        "mlp_dim": 9728,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen3-8b": {
        "vocab_size": 151936,
        "embed_dim": 4096,
        "mlp_dim": 12288,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen3-8b-base": {
        "vocab_size": 151936,
        "embed_dim": 4096,
        "mlp_dim": 12288,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen3-14b": {
        "vocab_size": 151936,
        "embed_dim": 5120,
        "mlp_dim": 17408,
        "num_layers": 40,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen3-14b-base": {
        "vocab_size": 151936,
        "embed_dim": 5120,
        "mlp_dim": 17408,
        "num_layers": 40,
        "num_heads": 40,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen3-32b": {
        "vocab_size": 151936,
        "embed_dim": 5120,
        "mlp_dim": 25600,
        "num_layers": 64,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
}

QWEN3_WEIGHTS = {
    "qwen3-0.6b": {"hf_id": "Qwen/Qwen3-0.6B", "gated": False, "safetensors": True},
    "qwen3-0.6b-base": {
        "hf_id": "Qwen/Qwen3-0.6B-Base",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-1.7b": {"hf_id": "Qwen/Qwen3-1.7B", "gated": False, "safetensors": True},
    "qwen3-1.7b-base": {
        "hf_id": "Qwen/Qwen3-1.7B-Base",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-4b": {"hf_id": "Qwen/Qwen3-4B", "gated": False, "safetensors": True},
    "qwen3-4b-base": {
        "hf_id": "Qwen/Qwen3-4B-Base",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-8b": {"hf_id": "Qwen/Qwen3-8B", "gated": False, "safetensors": True},
    "qwen3-8b-base": {
        "hf_id": "Qwen/Qwen3-8B-Base",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-14b": {"hf_id": "Qwen/Qwen3-14B", "gated": False, "safetensors": True},
    "qwen3-14b-base": {
        "hf_id": "Qwen/Qwen3-14B-Base",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-32b": {"hf_id": "Qwen/Qwen3-32B", "gated": False, "safetensors": True},
}
