EFFICIENTNETV2_MODEL_CONFIG = {
    "tf_efficientnetv2_s_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 300,
        "block_arch": "EfficientNetV2S",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_s.in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_s_in21k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 300,
        "block_arch": "EfficientNetV2S",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_s.in21k",
        "image_size": 300,
        "num_classes": 21843,
    },
    "tf_efficientnetv2_s_in21k_ft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 300,
        "block_arch": "EfficientNetV2S",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_s.in21k_ft_in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_m_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2M",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_m.in1k",
        "image_size": 384,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_m_in21k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2M",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_m.in21k",
        "image_size": 384,
        "num_classes": 21843,
    },
    "tf_efficientnetv2_m_in21k_ft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2M",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_m.in21k_ft_in1k",
        "image_size": 384,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_l_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2L",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_l.in1k",
        "image_size": 384,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_l_in21k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2L",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_l.in21k",
        "image_size": 384,
        "num_classes": 21843,
    },
    "tf_efficientnetv2_l_in21k_ft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2L",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_l.in21k_ft_in1k",
        "image_size": 384,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_xl_in21k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2XL",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_xl.in21k",
        "image_size": 384,
        "num_classes": 21843,
    },
    "tf_efficientnetv2_xl_in21k_ft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 384,
        "block_arch": "EfficientNetV2XL",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_xl.in21k_ft_in1k",
        "image_size": 384,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_b0_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "default_size": 192,
        "block_arch": "EfficientNetV2B",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_b0.in1k",
        "image_size": 192,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_b1_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.1,
        "default_size": 192,
        "block_arch": "EfficientNetV2B",
        "head_filters": 1280,
        "timm_id": "tf_efficientnetv2_b1.in1k",
        "image_size": 192,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_b2_in1k": {
        "width_coefficient": 1.1,
        "depth_coefficient": 1.2,
        "default_size": 208,
        "block_arch": "EfficientNetV2B",
        "head_filters": 1408,
        "timm_id": "tf_efficientnetv2_b2.in1k",
        "image_size": 208,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_b3_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "default_size": 240,
        "block_arch": "EfficientNetV2B",
        "head_filters": 1536,
        "timm_id": "tf_efficientnetv2_b3.in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
    "tf_efficientnetv2_b3_in21k_ft_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "default_size": 240,
        "block_arch": "EfficientNetV2B",
        "head_filters": 1536,
        "timm_id": "tf_efficientnetv2_b3.in21k_ft_in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
}

EFFICIENTNETV2_WEIGHT_CONFIG = {
    "tf_efficientnetv2_s_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_s_in1k.weights.h5",
    },
    "tf_efficientnetv2_s_in21k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_s_in21k.weights.h5",
    },
    "tf_efficientnetv2_s_in21k_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_s_in21k_ft_in1k.weights.h5",
    },
    "tf_efficientnetv2_m_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_m_in1k.weights.h5",
    },
    "tf_efficientnetv2_m_in21k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_m_in21k.weights.h5",
    },
    "tf_efficientnetv2_m_in21k_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_m_in21k_ft_in1k.weights.h5",
    },
    "tf_efficientnetv2_l_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_l_in1k.weights.h5",
    },
    "tf_efficientnetv2_l_in21k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_l_in21k.weights.h5",
    },
    "tf_efficientnetv2_l_in21k_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_l_in21k_ft_in1k.weights.h5",
    },
    "tf_efficientnetv2_xl_in21k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_xl_in21k.weights.h5",
    },
    "tf_efficientnetv2_xl_in21k_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_xl_in21k_ft_in1k.weights.h5",
    },
    "tf_efficientnetv2_b0_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_b0_in1k.weights.h5",
    },
    "tf_efficientnetv2_b1_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_b1_in1k.weights.h5",
    },
    "tf_efficientnetv2_b2_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_b2_in1k.weights.h5",
    },
    "tf_efficientnetv2_b3_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_b3_in1k.weights.h5",
    },
    "tf_efficientnetv2_b3_in21k_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.2/tf_efficientnetv2_b3_in21k_ft_in1k.weights.h5",
    },
}
