# Only the per-variant differences live here; everything common to all InternVL3
# checkpoints (vocab_size, norm_eps, rope_theta, tie_embeddings) is baked into
# the InternVLModel.__init__ defaults. The 1B-14B variants use the 300M ViT, the
# 38B/78B use the 6B ViT (the differing vision_* keys are kept per variant).
INTERNVL_CONFIG = {
    "internvl3-1b": {
        "embed_dim": 896,
        "mlp_dim": 4864,
        "num_layers": 24,
        "num_heads": 14,
        "num_kv_heads": 2,
        "vision_embed_dim": 1024,
        "vision_mlp_dim": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_attention_bias": True,
        "vision_qk_norm": False,
        "vision_norm_type": "layer_norm",
    },
    "internvl3-2b": {
        "embed_dim": 1536,
        "mlp_dim": 8960,
        "num_layers": 28,
        "num_heads": 12,
        "num_kv_heads": 2,
        "vision_embed_dim": 1024,
        "vision_mlp_dim": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_attention_bias": True,
        "vision_qk_norm": False,
        "vision_norm_type": "layer_norm",
    },
    "internvl3-8b": {
        "embed_dim": 3584,
        "mlp_dim": 18944,
        "num_layers": 28,
        "num_heads": 28,
        "num_kv_heads": 4,
        "vision_embed_dim": 1024,
        "vision_mlp_dim": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_attention_bias": True,
        "vision_qk_norm": False,
        "vision_norm_type": "layer_norm",
    },
    "internvl3-14b": {
        "embed_dim": 5120,
        "mlp_dim": 13824,
        "num_layers": 48,
        "num_heads": 40,
        "num_kv_heads": 8,
        "vision_embed_dim": 1024,
        "vision_mlp_dim": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_attention_bias": True,
        "vision_qk_norm": False,
        "vision_norm_type": "layer_norm",
    },
    "internvl3-38b": {
        "embed_dim": 5120,
        "mlp_dim": 27648,
        "num_layers": 64,
        "num_heads": 40,
        "num_kv_heads": 8,
        "vision_embed_dim": 3200,
        "vision_mlp_dim": 12800,
        "vision_num_layers": 45,
        "vision_num_heads": 25,
        "vision_attention_bias": False,
        "vision_qk_norm": True,
        "vision_norm_type": "rms_norm",
    },
    "internvl3-78b": {
        "embed_dim": 8192,
        "mlp_dim": 29568,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "vision_embed_dim": 3200,
        "vision_mlp_dim": 12800,
        "vision_num_layers": 45,
        "vision_num_heads": 25,
        "vision_attention_bias": False,
        "vision_qk_norm": True,
        "vision_norm_type": "rms_norm",
    },
}

INTERNVL_WEIGHTS_URLS = {
    "internvl3-1b": {
        "hf_id": "OpenGVLab/InternVL3-1B-hf",
        "gated": False,
        "safetensors": True,
    },
    "internvl3-2b": {
        "hf_id": "OpenGVLab/InternVL3-2B-hf",
        "gated": False,
        "safetensors": True,
    },
    "internvl3-8b": {
        "hf_id": "OpenGVLab/InternVL3-8B-hf",
        "gated": False,
        "safetensors": True,
    },
    "internvl3-14b": {
        "hf_id": "OpenGVLab/InternVL3-14B-hf",
        "gated": False,
        "safetensors": True,
    },
    "internvl3-38b": {
        "hf_id": "OpenGVLab/InternVL3-38B-hf",
        "gated": False,
        "safetensors": True,
    },
    "internvl3-78b": {
        "hf_id": "OpenGVLab/InternVL3-78B-hf",
        "gated": False,
        "safetensors": True,
    },
}
