EFFICIENTNET_MODEL_CONFIG = {
    "tf_efficientnet_b0_ns_jft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "dropout_rate": 0.2,
        "default_size": 224,
        "timm_id": "tf_efficientnet_b0.ns_jft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "tf_efficientnet_b0_ap_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "dropout_rate": 0.2,
        "default_size": 224,
        "timm_id": "tf_efficientnet_b0.ap_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "tf_efficientnet_b0_aa_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "dropout_rate": 0.2,
        "default_size": 224,
        "timm_id": "tf_efficientnet_b0.aa_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "tf_efficientnet_b0_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.0,
        "dropout_rate": 0.2,
        "default_size": 224,
        "timm_id": "tf_efficientnet_b0.in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "tf_efficientnet_b1_ns_jft_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.1,
        "dropout_rate": 0.2,
        "default_size": 240,
        "timm_id": "tf_efficientnet_b1.ns_jft_in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
    "tf_efficientnet_b1_ap_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.1,
        "dropout_rate": 0.2,
        "default_size": 240,
        "timm_id": "tf_efficientnet_b1.ap_in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
    "tf_efficientnet_b1_aa_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.1,
        "dropout_rate": 0.2,
        "default_size": 240,
        "timm_id": "tf_efficientnet_b1.aa_in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
    "tf_efficientnet_b1_in1k": {
        "width_coefficient": 1.0,
        "depth_coefficient": 1.1,
        "dropout_rate": 0.2,
        "default_size": 240,
        "timm_id": "tf_efficientnet_b1.in1k",
        "image_size": 240,
        "num_classes": 1000,
    },
    "tf_efficientnet_b2_ns_jft_in1k": {
        "width_coefficient": 1.1,
        "depth_coefficient": 1.2,
        "dropout_rate": 0.3,
        "default_size": 260,
        "timm_id": "tf_efficientnet_b2.ns_jft_in1k",
        "image_size": 260,
        "num_classes": 1000,
    },
    "tf_efficientnet_b2_ap_in1k": {
        "width_coefficient": 1.1,
        "depth_coefficient": 1.2,
        "dropout_rate": 0.3,
        "default_size": 260,
        "timm_id": "tf_efficientnet_b2.ap_in1k",
        "image_size": 260,
        "num_classes": 1000,
    },
    "tf_efficientnet_b2_aa_in1k": {
        "width_coefficient": 1.1,
        "depth_coefficient": 1.2,
        "dropout_rate": 0.3,
        "default_size": 260,
        "timm_id": "tf_efficientnet_b2.aa_in1k",
        "image_size": 260,
        "num_classes": 1000,
    },
    "tf_efficientnet_b2_in1k": {
        "width_coefficient": 1.1,
        "depth_coefficient": 1.2,
        "dropout_rate": 0.3,
        "default_size": 260,
        "timm_id": "tf_efficientnet_b2.in1k",
        "image_size": 260,
        "num_classes": 1000,
    },
    "tf_efficientnet_b3_ns_jft_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "dropout_rate": 0.3,
        "default_size": 300,
        "timm_id": "tf_efficientnet_b3.ns_jft_in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnet_b3_ap_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "dropout_rate": 0.3,
        "default_size": 300,
        "timm_id": "tf_efficientnet_b3.ap_in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnet_b3_aa_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "dropout_rate": 0.3,
        "default_size": 300,
        "timm_id": "tf_efficientnet_b3.aa_in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnet_b3_in1k": {
        "width_coefficient": 1.2,
        "depth_coefficient": 1.4,
        "dropout_rate": 0.3,
        "default_size": 300,
        "timm_id": "tf_efficientnet_b3.in1k",
        "image_size": 300,
        "num_classes": 1000,
    },
    "tf_efficientnet_b4_ns_jft_in1k": {
        "width_coefficient": 1.4,
        "depth_coefficient": 1.8,
        "dropout_rate": 0.4,
        "default_size": 380,
        "timm_id": "tf_efficientnet_b4.ns_jft_in1k",
        "image_size": 380,
        "num_classes": 1000,
    },
    "tf_efficientnet_b4_ap_in1k": {
        "width_coefficient": 1.4,
        "depth_coefficient": 1.8,
        "dropout_rate": 0.4,
        "default_size": 380,
        "timm_id": "tf_efficientnet_b4.ap_in1k",
        "image_size": 380,
        "num_classes": 1000,
    },
    "tf_efficientnet_b4_aa_in1k": {
        "width_coefficient": 1.4,
        "depth_coefficient": 1.8,
        "dropout_rate": 0.4,
        "default_size": 380,
        "timm_id": "tf_efficientnet_b4.aa_in1k",
        "image_size": 380,
        "num_classes": 1000,
    },
    "tf_efficientnet_b4_in1k": {
        "width_coefficient": 1.4,
        "depth_coefficient": 1.8,
        "dropout_rate": 0.4,
        "default_size": 380,
        "timm_id": "tf_efficientnet_b4.in1k",
        "image_size": 380,
        "num_classes": 1000,
    },
    "tf_efficientnet_b5_ns_jft_in1k": {
        "width_coefficient": 1.6,
        "depth_coefficient": 2.2,
        "dropout_rate": 0.4,
        "default_size": 456,
        "timm_id": "tf_efficientnet_b5.ns_jft_in1k",
        "image_size": 456,
        "num_classes": 1000,
    },
    "tf_efficientnet_b5_ap_in1k": {
        "width_coefficient": 1.6,
        "depth_coefficient": 2.2,
        "dropout_rate": 0.4,
        "default_size": 456,
        "timm_id": "tf_efficientnet_b5.ap_in1k",
        "image_size": 456,
        "num_classes": 1000,
    },
    "tf_efficientnet_b5_aa_in1k": {
        "width_coefficient": 1.6,
        "depth_coefficient": 2.2,
        "dropout_rate": 0.4,
        "default_size": 456,
        "timm_id": "tf_efficientnet_b5.aa_in1k",
        "image_size": 456,
        "num_classes": 1000,
    },
    "tf_efficientnet_b5_in1k": {
        "width_coefficient": 1.6,
        "depth_coefficient": 2.2,
        "dropout_rate": 0.4,
        "default_size": 456,
        "timm_id": "tf_efficientnet_b5.in1k",
        "image_size": 456,
        "num_classes": 1000,
    },
    "tf_efficientnet_b6_ns_jft_in1k": {
        "width_coefficient": 1.8,
        "depth_coefficient": 2.6,
        "dropout_rate": 0.5,
        "default_size": 528,
        "timm_id": "tf_efficientnet_b6.ns_jft_in1k",
        "image_size": 528,
        "num_classes": 1000,
    },
    "tf_efficientnet_b6_ap_in1k": {
        "width_coefficient": 1.8,
        "depth_coefficient": 2.6,
        "dropout_rate": 0.5,
        "default_size": 528,
        "timm_id": "tf_efficientnet_b6.ap_in1k",
        "image_size": 528,
        "num_classes": 1000,
    },
    "tf_efficientnet_b6_aa_in1k": {
        "width_coefficient": 1.8,
        "depth_coefficient": 2.6,
        "dropout_rate": 0.5,
        "default_size": 528,
        "timm_id": "tf_efficientnet_b6.aa_in1k",
        "image_size": 528,
        "num_classes": 1000,
    },
    "tf_efficientnet_b7_ns_jft_in1k": {
        "width_coefficient": 2.0,
        "depth_coefficient": 3.1,
        "dropout_rate": 0.5,
        "default_size": 600,
        "timm_id": "tf_efficientnet_b7.ns_jft_in1k",
        "image_size": 600,
        "num_classes": 1000,
    },
    "tf_efficientnet_b7_ap_in1k": {
        "width_coefficient": 2.0,
        "depth_coefficient": 3.1,
        "dropout_rate": 0.5,
        "default_size": 600,
        "timm_id": "tf_efficientnet_b7.ap_in1k",
        "image_size": 600,
        "num_classes": 1000,
    },
    "tf_efficientnet_b7_aa_in1k": {
        "width_coefficient": 2.0,
        "depth_coefficient": 3.1,
        "dropout_rate": 0.5,
        "default_size": 600,
        "timm_id": "tf_efficientnet_b7.aa_in1k",
        "image_size": 600,
        "num_classes": 1000,
    },
    "tf_efficientnet_b8_ap_in1k": {
        "width_coefficient": 2.2,
        "depth_coefficient": 3.6,
        "dropout_rate": 0.5,
        "default_size": 672,
        "timm_id": "tf_efficientnet_b8.ap_in1k",
        "image_size": 672,
        "num_classes": 1000,
    },
    "tf_efficientnet_l2_ns_jft_in1k": {
        "width_coefficient": 4.3,
        "depth_coefficient": 5.3,
        "dropout_rate": 0.5,
        "default_size": 800,
        "timm_id": "tf_efficientnet_l2.ns_jft_in1k",
        "image_size": 800,
        "num_classes": 1000,
    },
    "tf_efficientnet_l2_ns_jft_in1k_475": {
        "width_coefficient": 4.3,
        "depth_coefficient": 5.3,
        "dropout_rate": 0.5,
        "default_size": 800,
        "timm_id": "tf_efficientnet_l2.ns_jft_in1k_475",
        "image_size": 475,
        "num_classes": 1000,
    },
}

EFFICIENTNET_WEIGHT_CONFIG = {
    "tf_efficientnet_b0_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b0_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b0_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b0_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b0_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b0_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b0_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b0_in1k.weights.h5",
    },
    "tf_efficientnet_b1_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b1_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b1_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b1_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b1_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b1_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b1_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b1_in1k.weights.h5",
    },
    "tf_efficientnet_b2_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b2_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b2_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b2_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b2_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b2_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b2_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b2_in1k.weights.h5",
    },
    "tf_efficientnet_b3_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b3_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b3_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b3_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b3_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b3_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b3_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b3_in1k.weights.h5",
    },
    "tf_efficientnet_b4_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b4_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b4_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b4_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b4_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b4_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b4_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b4_in1k.weights.h5",
    },
    "tf_efficientnet_b5_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b5_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b5_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b5_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b5_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b5_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b5_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b5_in1k.weights.h5",
    },
    "tf_efficientnet_b6_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b6_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b6_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b6_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b6_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b6_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b7_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b7_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_b7_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b7_ap_in1k.weights.h5",
    },
    "tf_efficientnet_b7_aa_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b7_aa_in1k.weights.h5",
    },
    "tf_efficientnet_b8_ap_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_b8_ap_in1k.weights.h5",
    },
    "tf_efficientnet_l2_ns_jft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_l2_ns_jft_in1k.weights.h5",
    },
    "tf_efficientnet_l2_ns_jft_in1k_475": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/v0.1/tf_efficientnet_l2_ns_jft_in1k_475.weights.h5",
    },
}
