OWLV2_CONFIG = {
    "owlv2-base-patch16": {
        "vision_image_size": 960,
        "vision_patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_intermediate_size": 3072,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "text_hidden_dim": 512,
        "text_intermediate_size": 2048,
        "text_num_heads": 8,
        "projection_dim": 512,
    },
    "owlv2-base-patch16-ensemble": {
        "vision_image_size": 960,
        "vision_patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_intermediate_size": 3072,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "text_hidden_dim": 512,
        "text_intermediate_size": 2048,
        "text_num_heads": 8,
        "projection_dim": 512,
    },
    "owlv2-base-patch16-finetuned": {
        "vision_image_size": 960,
        "vision_patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_intermediate_size": 3072,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "text_hidden_dim": 512,
        "text_intermediate_size": 2048,
        "text_num_heads": 8,
        "projection_dim": 512,
    },
    "owlv2-large-patch14": {
        "vision_image_size": 1008,
        "vision_patch_size": 14,
        "vision_hidden_dim": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "text_hidden_dim": 768,
        "text_intermediate_size": 3072,
        "text_num_heads": 16,
        "projection_dim": 768,
    },
    "owlv2-large-patch14-ensemble": {
        "vision_image_size": 1008,
        "vision_patch_size": 14,
        "vision_hidden_dim": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "text_hidden_dim": 768,
        "text_intermediate_size": 3072,
        "text_num_heads": 16,
        "projection_dim": 768,
    },
    "owlv2-large-patch14-finetuned": {
        "vision_image_size": 1008,
        "vision_patch_size": 14,
        "vision_hidden_dim": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "text_hidden_dim": 768,
        "text_intermediate_size": 3072,
        "text_num_heads": 16,
        "projection_dim": 768,
    },
}

OWLV2_WEIGHTS_URLS = {
    "owlv2-base-patch16": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_base_patch16.weights.h5",
    },
    "owlv2-base-patch16-ensemble": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_base_patch16_ensemble.weights.h5",
    },
    "owlv2-base-patch16-finetuned": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_base_patch16_finetuned.weights.h5",
    },
    "owlv2-large-patch14": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_large_patch14.weights.h5",
    },
    "owlv2-large-patch14-ensemble": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_large_patch14_ensemble.weights.h5",
    },
    "owlv2-large-patch14-finetuned": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/owlv2/owlv2_large_patch14_finetuned.weights.h5",
    },
}
