SIGLIP_CONFIG = {
    "siglip_base_p16_224": {
        "image_size": 224,
        "patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "vision_mlp_dim": 3072,
        "vocab_size": 32000,
        "embed_dim": 768,
        "text_hidden_dim": 768,
        "text_num_layers": 12,
        "text_num_heads": 12,
        "text_mlp_dim": 3072,
        "max_seq_len": 64,
    },
    "siglip_base_p16_256": {
        "image_size": 256,
        "patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "vision_mlp_dim": 3072,
        "vocab_size": 32000,
        "embed_dim": 768,
        "text_hidden_dim": 768,
        "text_num_layers": 12,
        "text_num_heads": 12,
        "text_mlp_dim": 3072,
        "max_seq_len": 64,
    },
    "siglip_base_p16_multilingual_256": {
        "image_size": 256,
        "patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "vision_mlp_dim": 3072,
        "vocab_size": 250000,
        "embed_dim": 768,
        "text_hidden_dim": 768,
        "text_num_layers": 12,
        "text_num_heads": 12,
        "text_mlp_dim": 3072,
        "max_seq_len": 64,
    },
    "siglip_base_p16_384": {
        "image_size": 384,
        "patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "vision_mlp_dim": 3072,
        "vocab_size": 32000,
        "embed_dim": 768,
        "text_hidden_dim": 768,
        "text_num_layers": 12,
        "text_num_heads": 12,
        "text_mlp_dim": 3072,
        "max_seq_len": 64,
    },
    "siglip_base_p16_512": {
        "image_size": 512,
        "patch_size": 16,
        "vision_hidden_dim": 768,
        "vision_num_layers": 12,
        "vision_num_heads": 12,
        "vision_mlp_dim": 3072,
        "vocab_size": 32000,
        "embed_dim": 768,
        "text_hidden_dim": 768,
        "text_num_layers": 12,
        "text_num_heads": 12,
        "text_mlp_dim": 3072,
        "max_seq_len": 64,
    },
    "siglip_large_p16_256": {
        "image_size": 256,
        "patch_size": 16,
        "vision_hidden_dim": 1024,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_mlp_dim": 4096,
        "vocab_size": 32000,
        "embed_dim": 1024,
        "text_hidden_dim": 1024,
        "text_num_layers": 24,
        "text_num_heads": 16,
        "text_mlp_dim": 4096,
        "max_seq_len": 64,
    },
    "siglip_large_p16_384": {
        "image_size": 384,
        "patch_size": 16,
        "vision_hidden_dim": 1024,
        "vision_num_layers": 24,
        "vision_num_heads": 16,
        "vision_mlp_dim": 4096,
        "vocab_size": 32000,
        "embed_dim": 1024,
        "text_hidden_dim": 1024,
        "text_num_layers": 24,
        "text_num_heads": 16,
        "text_mlp_dim": 4096,
        "max_seq_len": 64,
    },
    "siglip_so400m_p14_224": {
        "image_size": 224,
        "patch_size": 14,
        "vision_hidden_dim": 1152,
        "vision_num_layers": 27,
        "vision_num_heads": 16,
        "vision_mlp_dim": 4304,
        "vocab_size": 32000,
        "embed_dim": 1152,
        "text_hidden_dim": 1152,
        "text_num_layers": 27,
        "text_num_heads": 16,
        "text_mlp_dim": 4304,
        "max_seq_len": 16,
    },
    "siglip_so400m_p14_384": {
        "image_size": 384,
        "patch_size": 14,
        "vision_hidden_dim": 1152,
        "vision_num_layers": 27,
        "vision_num_heads": 16,
        "vision_mlp_dim": 4304,
        "vocab_size": 32000,
        "embed_dim": 1152,
        "text_hidden_dim": 1152,
        "text_num_layers": 27,
        "text_num_heads": 16,
        "text_mlp_dim": 4304,
        "max_seq_len": 64,
    },
}

SIGLIP_WEIGHTS = {
    "siglip_base_p16_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_base_p16_224.weights.h5",
    },
    "siglip_base_p16_256": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_base_p16_256.weights.h5",
    },
    "siglip_base_p16_multilingual_256": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_base_p16_multilingual_256.weights.h5",
    },
    "siglip_base_p16_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_base_p16_384.weights.h5",
    },
    "siglip_base_p16_512": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_base_p16_512.weights.h5",
    },
    "siglip_large_p16_256": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_large_p16_256.weights.json",
    },
    "siglip_large_p16_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_large_p16_384.weights.json",
    },
    "siglip_so400m_p14_224": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_so400m_p14_224.weights.json",
    },
    "siglip_so400m_p14_384": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/siglip/siglip_so400m_p14_384.weights.json",
    },
}
