GLM4_MOE_CONFIG = {
    "glm-4.5": {
        "vocab_size": 151552,
        "embed_dim": 4096,
        "num_layers": 92,
        "num_heads": 96,
        "num_kv_heads": 8,
        "head_dim": 128,
        "mlp_dim": 10944,
        "moe_mlp_dim": 1408,
        "num_experts": 160,
        "num_experts_per_tok": 8,
        "n_shared_experts": 1,
        "n_group": 1,
        "topk_group": 1,
        "norm_topk_prob": True,
        "routed_scaling_factor": 1.0,
        "first_k_dense": 3,
        "partial_rotary_factor": 0.5,
        "use_qk_norm": False,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "attention_bias": True,
        "tie_embeddings": False,
    },
    "glm-4.5-air": {
        "vocab_size": 151552,
        "embed_dim": 4096,
        "num_layers": 46,
        "num_heads": 96,
        "num_kv_heads": 8,
        "head_dim": 128,
        "mlp_dim": 10944,
        "moe_mlp_dim": 1408,
        "num_experts": 128,
        "num_experts_per_tok": 8,
        "n_shared_experts": 1,
        "n_group": 1,
        "topk_group": 1,
        "norm_topk_prob": True,
        "routed_scaling_factor": 1.0,
        "first_k_dense": 1,
        "partial_rotary_factor": 0.5,
        "use_qk_norm": False,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "attention_bias": True,
        "tie_embeddings": False,
    },
    "glm-4.6": {
        "vocab_size": 151552,
        "embed_dim": 5120,
        "num_layers": 92,
        "num_heads": 96,
        "num_kv_heads": 8,
        "head_dim": 128,
        "mlp_dim": 12288,
        "moe_mlp_dim": 1536,
        "num_experts": 160,
        "num_experts_per_tok": 8,
        "n_shared_experts": 1,
        "n_group": 1,
        "topk_group": 1,
        "norm_topk_prob": True,
        "routed_scaling_factor": 1.0,
        "first_k_dense": 3,
        "partial_rotary_factor": 0.5,
        "use_qk_norm": False,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "attention_bias": True,
        "tie_embeddings": False,
    },
}

GLM4_MOE_WEIGHTS_URLS = {
    "glm-4.5": {
        "hf_id": "zai-org/GLM-4.5",
        "gated": False,
        "safetensors": True,
    },
    "glm-4.5-air": {
        "hf_id": "zai-org/GLM-4.5-Air",
        "gated": False,
        "safetensors": True,
    },
    "glm-4.6": {
        "hf_id": "zai-org/GLM-4.6",
        "gated": False,
        "safetensors": True,
    },
}
