DEPTHANYTHINGV2_CONFIG = {
    "depth_anything_v2_small": {
        "backbone_dim": 384,
        "backbone_depth": 12,
        "backbone_num_heads": 6,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [48, 96, 192, 384],
        "fusion_hidden_size": 64,
        "reassemble_factors": [4, 2, 1, 0.5],
    },
    "depth_anything_v2_base": {
        "backbone_dim": 768,
        "backbone_depth": 12,
        "backbone_num_heads": 12,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [96, 192, 384, 768],
        "fusion_hidden_size": 128,
        "reassemble_factors": [4, 2, 1, 0.5],
    },
    "depth_anything_v2_large": {
        "backbone_dim": 1024,
        "backbone_depth": 24,
        "backbone_num_heads": 16,
        "out_indices": [5, 12, 18, 24],
        "neck_hidden_sizes": [256, 512, 1024, 1024],
        "fusion_hidden_size": 256,
        "reassemble_factors": [4, 2, 1, 0.5],
    },
    "depth_anything_v2_metric_indoor_small": {
        "backbone_dim": 384,
        "backbone_depth": 12,
        "backbone_num_heads": 6,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [48, 96, 192, 384],
        "fusion_hidden_size": 64,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 20.0,
    },
    "depth_anything_v2_metric_indoor_base": {
        "backbone_dim": 768,
        "backbone_depth": 12,
        "backbone_num_heads": 12,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [96, 192, 384, 768],
        "fusion_hidden_size": 128,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 20.0,
    },
    "depth_anything_v2_metric_indoor_large": {
        "backbone_dim": 1024,
        "backbone_depth": 24,
        "backbone_num_heads": 16,
        "out_indices": [5, 12, 18, 24],
        "neck_hidden_sizes": [256, 512, 1024, 1024],
        "fusion_hidden_size": 256,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 20.0,
    },
    "depth_anything_v2_metric_outdoor_small": {
        "backbone_dim": 384,
        "backbone_depth": 12,
        "backbone_num_heads": 6,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [48, 96, 192, 384],
        "fusion_hidden_size": 64,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 80.0,
    },
    "depth_anything_v2_metric_outdoor_base": {
        "backbone_dim": 768,
        "backbone_depth": 12,
        "backbone_num_heads": 12,
        "out_indices": [3, 6, 9, 12],
        "neck_hidden_sizes": [96, 192, 384, 768],
        "fusion_hidden_size": 128,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 80.0,
    },
    "depth_anything_v2_metric_outdoor_large": {
        "backbone_dim": 1024,
        "backbone_depth": 24,
        "backbone_num_heads": 16,
        "out_indices": [5, 12, 18, 24],
        "neck_hidden_sizes": [256, 512, 1024, 1024],
        "fusion_hidden_size": 256,
        "reassemble_factors": [4, 2, 1, 0.5],
        "depth_estimation_type": "metric",
        "max_depth": 80.0,
    },
}

DEPTHANYTHINGV2_WEIGHTS = {
    "depth_anything_v2_small": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_small.weights.h5",
    },
    "depth_anything_v2_base": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_base.weights.h5",
    },
    "depth_anything_v2_large": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_large.weights.h5",
    },
    "depth_anything_v2_metric_indoor_small": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_indoor_small.weights.h5",
    },
    "depth_anything_v2_metric_indoor_base": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_indoor_base.weights.h5",
    },
    "depth_anything_v2_metric_indoor_large": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_indoor_large.weights.h5",
    },
    "depth_anything_v2_metric_outdoor_small": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_outdoor_small.weights.h5",
    },
    "depth_anything_v2_metric_outdoor_base": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_outdoor_base.weights.h5",
    },
    "depth_anything_v2_metric_outdoor_large": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/depth-anything-v2/depth_anything_v2_metric_outdoor_large.weights.h5",
    },
}
