MASK2FORMER_CONFIG = {
    "mask2former-swin-tiny-coco-instance": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 6, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 100,
        "num_classes": 80,
        "image_size": 384,
    },
    "mask2former-swin-small-coco-instance": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 100,
        "num_classes": 80,
        "image_size": 384,
    },
    "mask2former-swin-base-coco-instance": {
        "backbone_embed_dim": 128,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (4, 8, 16, 32),
        "backbone_window_size": 12,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 100,
        "num_classes": 80,
        "image_size": 384,
    },
    "mask2former-swin-large-coco-instance": {
        "backbone_embed_dim": 192,
        "backbone_depths": (2, 2, 18, 2),
        "backbone_num_heads": (6, 12, 24, 48),
        "backbone_window_size": 12,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 200,
        "num_classes": 80,
        "image_size": 384,
    },
    "mask2former-swin-tiny-ade-semantic": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 6, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 100,
        "num_classes": 150,
        "image_size": 512,
    },
    "mask2former-swin-tiny-coco-panoptic": {
        "backbone_embed_dim": 96,
        "backbone_depths": (2, 2, 6, 2),
        "backbone_num_heads": (3, 6, 12, 24),
        "backbone_window_size": 7,
        "hidden_dim": 256,
        "mask_feature_size": 256,
        "encoder_num_layers": 6,
        "encoder_ffn_dim": 1024,
        "decoder_num_layers": 9,
        "decoder_ffn_dim": 2048,
        "num_heads": 8,
        "num_queries": 100,
        "num_classes": 133,
        "image_size": 384,
    },
}

MASK2FORMER_WEIGHTS = {
    "mask2former-swin-tiny-coco-instance": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-tiny-coco-instance.weights.h5",
    },
    "mask2former-swin-small-coco-instance": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-small-coco-instance.weights.h5",
    },
    "mask2former-swin-base-coco-instance": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-base-coco-instance.weights.h5",
    },
    "mask2former-swin-large-coco-instance": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-large-coco-instance.weights.h5",
    },
    "mask2former-swin-tiny-ade-semantic": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-tiny-ade-semantic.weights.h5",
    },
    "mask2former-swin-tiny-coco-panoptic": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/mask2former/mask2former-swin-tiny-coco-panoptic.weights.h5",
    },
}
