QWEN2_CONFIG = {
    "qwen2-0.5b": {
        "vocab_size": 151936,
        "embed_dim": 896,
        "mlp_dim": 4864,
        "num_layers": 24,
        "num_heads": 14,
        "num_kv_heads": 2,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen2-0.5b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 896,
        "mlp_dim": 4864,
        "num_layers": 24,
        "num_heads": 14,
        "num_kv_heads": 2,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen2-1.5b": {
        "vocab_size": 151936,
        "embed_dim": 1536,
        "mlp_dim": 8960,
        "num_layers": 28,
        "num_heads": 12,
        "num_kv_heads": 2,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen2-1.5b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 1536,
        "mlp_dim": 8960,
        "num_layers": 28,
        "num_heads": 12,
        "num_kv_heads": 2,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": True,
    },
    "qwen2-7b": {
        "vocab_size": 152064,
        "embed_dim": 3584,
        "mlp_dim": 18944,
        "num_layers": 28,
        "num_heads": 28,
        "num_kv_heads": 4,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen2-7b-instruct": {
        "vocab_size": 152064,
        "embed_dim": 3584,
        "mlp_dim": 18944,
        "num_layers": 28,
        "num_heads": 28,
        "num_kv_heads": 4,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen2-72b": {
        "vocab_size": 152064,
        "embed_dim": 8192,
        "mlp_dim": 29568,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "norm_eps": 1e-5,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
    "qwen2-72b-instruct": {
        "vocab_size": 152064,
        "embed_dim": 8192,
        "mlp_dim": 29568,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "tie_embeddings": False,
    },
}

QWEN2_WEIGHTS = {
    "qwen2-0.5b": {"hf_id": "Qwen/Qwen2-0.5B", "gated": False, "safetensors": True},
    "qwen2-0.5b-instruct": {
        "hf_id": "Qwen/Qwen2-0.5B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2-1.5b": {"hf_id": "Qwen/Qwen2-1.5B", "gated": False, "safetensors": True},
    "qwen2-1.5b-instruct": {
        "hf_id": "Qwen/Qwen2-1.5B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2-7b": {"hf_id": "Qwen/Qwen2-7B", "gated": False, "safetensors": True},
    "qwen2-7b-instruct": {
        "hf_id": "Qwen/Qwen2-7B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2-72b": {"hf_id": "Qwen/Qwen2-72B", "gated": False, "safetensors": True},
    "qwen2-72b-instruct": {
        "hf_id": "Qwen/Qwen2-72B-Instruct",
        "gated": False,
        "safetensors": True,
    },
}
