# Qwen3-VL — third-gen Qwen multimodal LLM. Bigger architectural deltas:
#   * Text decoder is Qwen3 (QK-norm in attention, no qkv bias), rope_theta 5e6,
#     and INTERLEAVED M-RoPE (mrope_interleaved) instead of sectioned.
#   * Vision tower: Conv3d (with bias) patch embed (patch_size 16), bilinearly
#     interpolated LEARNED position embeddings, LayerNorm + (non-gated) GELU MLP
#     blocks, full attention (no windowing), and DeepStack — features from a few
#     vision layers are injected into the first text layers.
#
# Dense sizes only (2B/4B/8B/32B); each ships as -Instruct and -Thinking, which
# share an architecture (they differ only in weights). The 30B-A3B / 235B-A22B
# checkpoints are Mixture-of-Experts (model_type "qwen3_vl_moe") and need a
# separate MoE implementation, so they are absent here.
#
# Load by variant name (converts on the fly from the public HF checkpoint;
# raw hf: ids still work):
#     Qwen3VLModel.from_weights("qwen3-vl-4b-instruct")
#     Qwen3VLModel.from_weights("qwen3-vl-8b-thinking")

QWEN3_VL_CONFIG = {
    "qwen3-vl-2b-instruct": {
        "vocab_size": 151936,
        "hidden_size": 2048,
        "intermediate_size": 6144,
        "num_hidden_layers": 28,
        "num_attention_heads": 16,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2048,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-2b-thinking": {
        "vocab_size": 151936,
        "hidden_size": 2048,
        "intermediate_size": 6144,
        "num_hidden_layers": 28,
        "num_attention_heads": 16,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2048,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-4b-instruct": {
        "vocab_size": 151936,
        "hidden_size": 2560,
        "intermediate_size": 9728,
        "num_hidden_layers": 36,
        "num_attention_heads": 32,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2560,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-4b-thinking": {
        "vocab_size": 151936,
        "hidden_size": 2560,
        "intermediate_size": 9728,
        "num_hidden_layers": 36,
        "num_attention_heads": 32,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2560,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-8b-instruct": {
        "vocab_size": 151936,
        "hidden_size": 4096,
        "intermediate_size": 12288,
        "num_hidden_layers": 36,
        "num_attention_heads": 32,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 4096,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-8b-thinking": {
        "vocab_size": 151936,
        "hidden_size": 4096,
        "intermediate_size": 12288,
        "num_hidden_layers": 36,
        "num_attention_heads": 32,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 4096,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-32b-instruct": {
        "vocab_size": 151936,
        "hidden_size": 5120,
        "intermediate_size": 25600,
        "num_hidden_layers": 64,
        "num_attention_heads": 64,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 5120,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-32b-thinking": {
        "vocab_size": 151936,
        "hidden_size": 5120,
        "intermediate_size": 25600,
        "num_hidden_layers": 64,
        "num_attention_heads": 64,
        "num_key_value_heads": 8,
        "head_dim": 128,
        "rms_norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_word_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 5120,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
}

QWEN3_VL_TOKENS = {
    "image_token_id": 151655,
    "video_token_id": 151656,
    "vision_start_token_id": 151652,
    "vision_end_token_id": 151653,
}

# Release weights (public Qwen repos; on-the-fly transfer_from_hf). Keys mirror
# QWEN3_VL_CONFIG -> `from_weights("qwen3-vl-4b-instruct")`.
QWEN3_VL_WEIGHTS = {
    "qwen3-vl-2b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-2B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-2b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-2B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-4b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-4B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-4b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-4B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-8b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-8B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-8b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-8B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-32b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-32B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-32b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-32B-Thinking",
        "gated": False,
        "safetensors": True,
    },
}
