QWEN3_VL_CONFIG = {
    "qwen3-vl-2b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 2048,
        "mlp_dim": 6144,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2048,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-2b-thinking": {
        "vocab_size": 151936,
        "embed_dim": 2048,
        "mlp_dim": 6144,
        "num_layers": 28,
        "num_heads": 16,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2048,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-4b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 2560,
        "mlp_dim": 9728,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2560,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-4b-thinking": {
        "vocab_size": 151936,
        "embed_dim": 2560,
        "mlp_dim": 9728,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": True,
        "vision_depth": 24,
        "vision_hidden_size": 1024,
        "vision_intermediate_size": 4096,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2560,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (5, 11, 17),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-8b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 4096,
        "mlp_dim": 12288,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 4096,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-8b-thinking": {
        "vocab_size": 151936,
        "embed_dim": 4096,
        "mlp_dim": 12288,
        "num_layers": 36,
        "num_heads": 32,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 4096,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-32b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 5120,
        "mlp_dim": 25600,
        "num_layers": 64,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 5120,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen3-vl-32b-thinking": {
        "vocab_size": 151936,
        "embed_dim": 5120,
        "mlp_dim": 25600,
        "num_layers": 64,
        "num_heads": 64,
        "num_kv_heads": 8,
        "head_dim": 128,
        "norm_eps": 1e-6,
        "rope_theta": 5000000.0,
        "mrope_section": (24, 20, 20),
        "tie_embeddings": False,
        "vision_depth": 27,
        "vision_hidden_size": 1152,
        "vision_intermediate_size": 4304,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 5120,
        "vision_hidden_act": "gelu_pytorch_tanh",
        "num_position_embeddings": 2304,
        "deepstack_visual_indexes": (8, 16, 24),
        "patch_size": 16,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
}

QWEN3_VL_TOKENS = {
    "image_token_id": 151655,
    "video_token_id": 151656,
    "vision_start_token_id": 151652,
    "vision_end_token_id": 151653,
}

QWEN3_VL_WEIGHTS_URLS = {
    "qwen3-vl-2b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-2B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-2b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-2B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-4b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-4B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-4b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-4B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-8b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-8B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-8b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-8B-Thinking",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-32b-instruct": {
        "hf_id": "Qwen/Qwen3-VL-32B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen3-vl-32b-thinking": {
        "hf_id": "Qwen/Qwen3-VL-32B-Thinking",
        "gated": False,
        "safetensors": True,
    },
}
