CLIP_CONFIG = {
    "clip_vit_base_16": {
        "embed_dim": 512,
        "input_image_shape": 224,
        "vision_layers": 12,
        "vision_width": 768,
        "vision_patch_size": 16,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 512,
        "transformer_heads": 8,
        "transformer_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "quick_gelu",
    },
    "clip_vit_base_32": {
        "embed_dim": 512,
        "input_image_shape": 224,
        "vision_layers": 12,
        "vision_width": 768,
        "vision_patch_size": 32,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 512,
        "transformer_heads": 8,
        "transformer_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "quick_gelu",
    },
    "clip_vit_large_14": {
        "embed_dim": 768,
        "input_image_shape": 224,
        "vision_layers": 24,
        "vision_width": 1024,
        "vision_patch_size": 14,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 768,
        "transformer_heads": 12,
        "transformer_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "quick_gelu",
    },
    "clip_vit_large_14_336": {
        "embed_dim": 768,
        "input_image_shape": 336,
        "vision_layers": 24,
        "vision_width": 1024,
        "vision_patch_size": 14,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 768,
        "transformer_heads": 12,
        "transformer_layers": 12,
        "vision_mlp_ratio": 4.0,
        "text_mlp_ratio": 4.0,
        "hidden_act": "quick_gelu",
    },
    "clip_vit_g_14": {
        "embed_dim": 1024,
        "input_image_shape": 224,
        "vision_layers": 40,
        "vision_width": 1408,
        "vision_patch_size": 14,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 1024,
        "transformer_heads": 16,
        "transformer_layers": 24,
        "vision_mlp_ratio": 6144 / 1408,
        "text_mlp_ratio": 4096 / 1024,
        "hidden_act": "gelu",
    },
    "clip_vit_bigg_14": {
        "embed_dim": 1280,
        "input_image_shape": 224,
        "vision_layers": 48,
        "vision_width": 1664,
        "vision_patch_size": 14,
        "context_length": 77,
        "vocab_size": 49408,
        "transformer_width": 1280,
        "transformer_heads": 20,
        "transformer_layers": 32,
        "vision_mlp_ratio": 8192 / 1664,
        "text_mlp_ratio": 5120 / 1280,
        "hidden_act": "gelu",
    },
}

CLIP_WEIGHTS = {
    "clip_vit_base_16": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_base_16.weights.h5",
    },
    "clip_vit_base_32": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_base_32.weights.h5",
    },
    "clip_vit_large_14": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_large_14.weights.h5",
    },
    "clip_vit_large_14_336": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_large_14_336.weights.h5",
    },
    "clip_vit_g_14": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_g_14.weights.json",
    },
    "clip_vit_bigg_14": {
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/clip/clip_vit_bigg_14.weights.json",
    },
}
