DEBERTA_V3_MODEL_CONFIG = {
    "deberta_v3_xsmall": {
        "vocab_size": 128100,
        "embed_dim": 384,
        "num_layers": 12,
        "num_heads": 6,
        "mlp_dim": 1536,
        "max_position_embeddings": 512,
        "max_relative_positions": 512,
        "position_buckets": 256,
        "pos_att_type": ["p2c", "c2p"],
        "norm_rel_ebd": True,
        "conv_kernel_size": 0,
        "conv_act": "gelu",
        "hidden_act": "gelu",
        "layer_norm_eps": 1e-7,
        "pad_token_id": 0,
    },
    "deberta_v3_small": {
        "vocab_size": 128100,
        "embed_dim": 768,
        "num_layers": 6,
        "num_heads": 12,
        "mlp_dim": 3072,
        "max_position_embeddings": 512,
        "max_relative_positions": 512,
        "position_buckets": 256,
        "pos_att_type": ["p2c", "c2p"],
        "norm_rel_ebd": True,
        "conv_kernel_size": 0,
        "conv_act": "gelu",
        "hidden_act": "gelu",
        "layer_norm_eps": 1e-7,
        "pad_token_id": 0,
    },
    "deberta_v3_base": {
        "vocab_size": 128100,
        "embed_dim": 768,
        "num_layers": 12,
        "num_heads": 12,
        "mlp_dim": 3072,
        "max_position_embeddings": 512,
        "max_relative_positions": 512,
        "position_buckets": 256,
        "pos_att_type": ["p2c", "c2p"],
        "norm_rel_ebd": True,
        "conv_kernel_size": 0,
        "conv_act": "gelu",
        "hidden_act": "gelu",
        "layer_norm_eps": 1e-7,
        "pad_token_id": 0,
    },
    "deberta_v3_large": {
        "vocab_size": 128100,
        "embed_dim": 1024,
        "num_layers": 24,
        "num_heads": 16,
        "mlp_dim": 4096,
        "max_position_embeddings": 512,
        "max_relative_positions": 512,
        "position_buckets": 256,
        "pos_att_type": ["p2c", "c2p"],
        "norm_rel_ebd": True,
        "conv_kernel_size": 0,
        "conv_act": "gelu",
        "hidden_act": "gelu",
        "layer_norm_eps": 1e-7,
        "pad_token_id": 0,
    },
}

DEBERTA_V3_WEIGHT_CONFIG = {
    "deberta_v3_xsmall": {
        "model": "deberta_v3_xsmall",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/deberta/deberta_v3_xsmall.weights.h5",
    },
    "deberta_v3_small": {
        "model": "deberta_v3_small",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/deberta/deberta_v3_small.weights.h5",
    },
    "deberta_v3_base": {
        "model": "deberta_v3_base",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/deberta/deberta_v3_base.weights.h5",
    },
    "deberta_v3_large": {
        "model": "deberta_v3_large",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/deberta/deberta_v3_large.weights.h5",
    },
}

DEBERTA_V3_VOCAB_URL = "https://github.com/IMvision12/KerasFormers/releases/download/deberta/deberta_v3_spm.model"
