CONVNEXTV2_MODEL_CONFIG = {
    "convnextv2_atto_fcmae_ft_in1k": {
        "depths": [2, 2, 6, 2],
        "projection_dims": [40, 80, 160, 320],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_atto.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_femto_fcmae_ft_in1k": {
        "depths": [2, 2, 6, 2],
        "projection_dims": [48, 96, 192, 384],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_femto.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_pico_fcmae_ft_in1k": {
        "depths": [2, 2, 6, 2],
        "projection_dims": [64, 128, 256, 512],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_pico.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_nano_fcmae_ft_in1k": {
        "depths": [2, 2, 8, 2],
        "projection_dims": [80, 160, 320, 640],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_nano.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_nano_fcmae_ft_in22k_in1k": {
        "depths": [2, 2, 8, 2],
        "projection_dims": [80, 160, 320, 640],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_nano.fcmae_ft_in22k_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_nano_fcmae_ft_in22k_in1k_384": {
        "depths": [2, 2, 8, 2],
        "projection_dims": [80, 160, 320, 640],
        "use_conv": True,
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_nano.fcmae_ft_in22k_in1k_384",
        "image_size": 384,
        "num_classes": 1000,
    },
    "convnextv2_tiny_fcmae_ft_in1k": {
        "depths": [3, 3, 9, 3],
        "projection_dims": [96, 192, 384, 768],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_tiny.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_tiny_fcmae_ft_in22k_in1k": {
        "depths": [3, 3, 9, 3],
        "projection_dims": [96, 192, 384, 768],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_tiny.fcmae_ft_in22k_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_tiny_fcmae_ft_in22k_in1k_384": {
        "depths": [3, 3, 9, 3],
        "projection_dims": [96, 192, 384, 768],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_tiny.fcmae_ft_in22k_in1k_384",
        "image_size": 384,
        "num_classes": 1000,
    },
    "convnextv2_base_fcmae_ft_in1k": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [128, 256, 512, 1024],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_base.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_base_fcmae_ft_in22k_in1k": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [128, 256, 512, 1024],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_base.fcmae_ft_in22k_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_base_fcmae_ft_in22k_in1k_384": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [128, 256, 512, 1024],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_base.fcmae_ft_in22k_in1k_384",
        "image_size": 384,
        "num_classes": 1000,
    },
    "convnextv2_large_fcmae_ft_in1k": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [192, 384, 768, 1536],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_large.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_large_fcmae_ft_in22k_in1k": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [192, 384, 768, 1536],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_large.fcmae_ft_in22k_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_large_fcmae_ft_in22k_in1k_384": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [192, 384, 768, 1536],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_large.fcmae_ft_in22k_in1k_384",
        "image_size": 384,
        "num_classes": 1000,
    },
    "convnextv2_huge_fcmae_ft_in1k": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [352, 704, 1408, 2816],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_huge.fcmae_ft_in1k",
        "image_size": 224,
        "num_classes": 1000,
    },
    "convnextv2_huge_fcmae_ft_in22k_in1k_384": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [352, 704, 1408, 2816],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_huge.fcmae_ft_in22k_in1k_384",
        "image_size": 384,
        "num_classes": 1000,
    },
    "convnextv2_huge_fcmae_ft_in22k_in1k_512": {
        "depths": [3, 3, 27, 3],
        "projection_dims": [352, 704, 1408, 2816],
        "use_grn": True,
        "layer_scale_init_value": None,
        "timm_id": "convnextv2_huge.fcmae_ft_in22k_in1k_512",
        "image_size": 512,
        "num_classes": 1000,
    },
}

CONVNEXTV2_WEIGHT_CONFIG = {
    "convnextv2_atto_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_atto_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_femto_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_femto_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_pico_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_pico_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_nano_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_nano_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_nano_fcmae_ft_in22k_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_nano_fcmae_ft_in22k_in1k.weights.h5",
    },
    "convnextv2_nano_fcmae_ft_in22k_in1k_384": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_nano_fcmae_ft_in22k_in1k_384.weights.h5",
    },
    "convnextv2_tiny_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_tiny_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_tiny_fcmae_ft_in22k_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_tiny_fcmae_ft_in22k_in1k.weights.h5",
    },
    "convnextv2_tiny_fcmae_ft_in22k_in1k_384": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_tiny_fcmae_ft_in22k_in1k_384.weights.h5",
    },
    "convnextv2_base_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_base_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_base_fcmae_ft_in22k_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_base_fcmae_ft_in22k_in1k.weights.h5",
    },
    "convnextv2_base_fcmae_ft_in22k_in1k_384": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_base_fcmae_ft_in22k_in1k_384.weights.h5",
    },
    "convnextv2_large_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_large_fcmae_ft_in1k.weights.h5",
    },
    "convnextv2_large_fcmae_ft_in22k_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_large_fcmae_ft_in22k_in1k.weights.h5",
    },
    "convnextv2_large_fcmae_ft_in22k_in1k_384": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_large_fcmae_ft_in22k_in1k_384.weights.h5",
    },
    "convnextv2_huge_fcmae_ft_in1k": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_huge_fcmae_ft_in1k.weights.json",
    },
    "convnextv2_huge_fcmae_ft_in22k_in1k_384": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_huge_fcmae_ft_in22k_in1k_384.weights.json",
    },
    "convnextv2_huge_fcmae_ft_in22k_in1k_512": {
        "url": "https://github.com/IMvision12/keras-models/releases/download/convnext/convnextv2_huge_fcmae_ft_in22k_in1k_512.weights.json",
    },
}
