NEXTVIT_MODEL_CONFIG = {
    "nextvit_small": {
        "depths": [3, 4, 10, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 224,
        "num_classes": 1000,
    },
    "nextvit_small_384": {
        "depths": [3, 4, 10, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 384,
        "num_classes": 1000,
    },
    "nextvit_base": {
        "depths": [3, 4, 20, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 224,
        "num_classes": 1000,
    },
    "nextvit_base_384": {
        "depths": [3, 4, 20, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 384,
        "num_classes": 1000,
    },
    "nextvit_large": {
        "depths": [3, 4, 30, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 224,
        "num_classes": 1000,
    },
    "nextvit_large_384": {
        "depths": [3, 4, 30, 3],
        "stem_chs": [64, 32, 64],
        "head_dim": 32,
        "mix_block_ratio": 0.75,
        "sr_ratios": [8, 4, 2, 1],
        "drop_path_rate": 0.1,
        "image_size": 384,
        "num_classes": 1000,
    },
}

NEXTVIT_WEIGHT_CONFIG = {
    "nextvit_small_bd_in1k": {
        "model": "nextvit_small",
        "timm_id": "nextvit_small.bd_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_small_bd_in1k.weights.h5",
    },
    "nextvit_small_bd_in1k_384": {
        "model": "nextvit_small_384",
        "timm_id": "nextvit_small.bd_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_small_bd_in1k_384.weights.h5",
    },
    "nextvit_small_bd_ssld_6m_in1k": {
        "model": "nextvit_small",
        "timm_id": "nextvit_small.bd_ssld_6m_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_small_bd_ssld_6m_in1k.weights.h5",
    },
    "nextvit_small_bd_ssld_6m_in1k_384": {
        "model": "nextvit_small_384",
        "timm_id": "nextvit_small.bd_ssld_6m_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_small_bd_ssld_6m_in1k_384.weights.h5",
    },
    "nextvit_base_bd_in1k": {
        "model": "nextvit_base",
        "timm_id": "nextvit_base.bd_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_base_bd_in1k.weights.h5",
    },
    "nextvit_base_bd_in1k_384": {
        "model": "nextvit_base_384",
        "timm_id": "nextvit_base.bd_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_base_bd_in1k_384.weights.h5",
    },
    "nextvit_base_bd_ssld_6m_in1k": {
        "model": "nextvit_base",
        "timm_id": "nextvit_base.bd_ssld_6m_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_base_bd_ssld_6m_in1k.weights.h5",
    },
    "nextvit_base_bd_ssld_6m_in1k_384": {
        "model": "nextvit_base_384",
        "timm_id": "nextvit_base.bd_ssld_6m_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_base_bd_ssld_6m_in1k_384.weights.h5",
    },
    "nextvit_large_bd_in1k": {
        "model": "nextvit_large",
        "timm_id": "nextvit_large.bd_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_large_bd_in1k.weights.h5",
    },
    "nextvit_large_bd_in1k_384": {
        "model": "nextvit_large_384",
        "timm_id": "nextvit_large.bd_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_large_bd_in1k_384.weights.h5",
    },
    "nextvit_large_bd_ssld_6m_in1k": {
        "model": "nextvit_large",
        "timm_id": "nextvit_large.bd_ssld_6m_in1k",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_large_bd_ssld_6m_in1k.weights.h5",
    },
    "nextvit_large_bd_ssld_6m_in1k_384": {
        "model": "nextvit_large_384",
        "timm_id": "nextvit_large.bd_ssld_6m_in1k_384",
        "url": "https://github.com/IMvision12/keras-models/releases/download/nextvit/nextvit_large_bd_ssld_6m_in1k_384.weights.h5",
    },
}
