"""PiT variant registry (timm-ported)."""

PIT_MODEL_CONFIG = {
    "pit_xs": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [96, 192, 384],
        "depth": [2, 6, 4],
        "heads": [2, 4, 8],
        "mlp_ratio": 4,
        "distilled": False,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_xs_distilled": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [96, 192, 384],
        "depth": [2, 6, 4],
        "heads": [2, 4, 8],
        "mlp_ratio": 4,
        "distilled": True,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_ti": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [64, 128, 256],
        "depth": [2, 6, 4],
        "heads": [2, 4, 8],
        "mlp_ratio": 4,
        "distilled": False,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_ti_distilled": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [64, 128, 256],
        "depth": [2, 6, 4],
        "heads": [2, 4, 8],
        "mlp_ratio": 4,
        "distilled": True,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_s": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [144, 288, 576],
        "depth": [2, 6, 4],
        "heads": [3, 6, 12],
        "mlp_ratio": 4,
        "distilled": False,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_s_distilled": {
        "patch_size": 16,
        "stride": 8,
        "embed_dim": [144, 288, 576],
        "depth": [2, 6, 4],
        "heads": [3, 6, 12],
        "mlp_ratio": 4,
        "distilled": True,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_b": {
        "patch_size": 14,
        "stride": 7,
        "embed_dim": [256, 512, 1024],
        "depth": [3, 6, 4],
        "heads": [4, 8, 16],
        "mlp_ratio": 4,
        "distilled": False,
        "image_size": 224,
        "num_classes": 1000,
    },
    "pit_b_distilled": {
        "patch_size": 14,
        "stride": 7,
        "embed_dim": [256, 512, 1024],
        "depth": [3, 6, 4],
        "heads": [4, 8, 16],
        "mlp_ratio": 4,
        "distilled": True,
        "image_size": 224,
        "num_classes": 1000,
    },
}

PIT_WEIGHT_CONFIG = {
    "pit_xs_224_in1k": {
        "model": "pit_xs",
        "timm_id": "pit_xs_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_xs_224_in1k.weights.h5",
    },
    "pit_xs_distilled_224_in1k": {
        "model": "pit_xs_distilled",
        "timm_id": "pit_xs_distilled_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_xs_distilled_224_in1k.weights.h5",
    },
    "pit_ti_224_in1k": {
        "model": "pit_ti",
        "timm_id": "pit_ti_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_ti_224_in1k.weights.h5",
    },
    "pit_ti_distilled_224_in1k": {
        "model": "pit_ti_distilled",
        "timm_id": "pit_ti_distilled_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_ti_distilled_224_in1k.weights.h5",
    },
    "pit_s_224_in1k": {
        "model": "pit_s",
        "timm_id": "pit_s_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_s_224_in1k.weights.h5",
    },
    "pit_s_distilled_224_in1k": {
        "model": "pit_s_distilled",
        "timm_id": "pit_s_distilled_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_s_distilled_224_in1k.weights.h5",
    },
    "pit_b_224_in1k": {
        "model": "pit_b",
        "timm_id": "pit_b_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_b_224_in1k.weights.h5",
    },
    "pit_b_distilled_224_in1k": {
        "model": "pit_b_distilled",
        "timm_id": "pit_b_distilled_224.in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify3/pit_b_distilled_224_in1k.weights.h5",
    },
}
