QWEN2_5_VL_CONFIG = {
    "qwen2.5-vl-3b-instruct": {
        "vocab_size": 151936,
        "embed_dim": 2048,
        "mlp_dim": 11008,
        "num_layers": 36,
        "num_heads": 16,
        "num_kv_heads": 2,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "mrope_section": (16, 24, 24),
        "tie_embeddings": True,
        "vision_depth": 32,
        "vision_hidden_size": 1280,
        "vision_intermediate_size": 3420,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 2048,
        "window_size": 112,
        "fullatt_block_indexes": (7, 15, 23, 31),
        "patch_size": 14,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen2.5-vl-7b-instruct": {
        "vocab_size": 152064,
        "embed_dim": 3584,
        "mlp_dim": 18944,
        "num_layers": 28,
        "num_heads": 28,
        "num_kv_heads": 4,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "mrope_section": (16, 24, 24),
        "tie_embeddings": False,
        "vision_depth": 32,
        "vision_hidden_size": 1280,
        "vision_intermediate_size": 3420,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 3584,
        "window_size": 112,
        "fullatt_block_indexes": (7, 15, 23, 31),
        "patch_size": 14,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen2.5-vl-32b-instruct": {
        "vocab_size": 152064,
        "embed_dim": 5120,
        "mlp_dim": 27648,
        "num_layers": 64,
        "num_heads": 40,
        "num_kv_heads": 8,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "mrope_section": (16, 24, 24),
        "tie_embeddings": False,
        "vision_depth": 32,
        "vision_hidden_size": 1280,
        "vision_intermediate_size": 3456,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 5120,
        "window_size": 112,
        "fullatt_block_indexes": (7, 15, 23, 31),
        "patch_size": 14,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
    "qwen2.5-vl-72b-instruct": {
        "vocab_size": 152064,
        "embed_dim": 8192,
        "mlp_dim": 29568,
        "num_layers": 80,
        "num_heads": 64,
        "num_kv_heads": 8,
        "norm_eps": 1e-6,
        "rope_theta": 1000000.0,
        "mrope_section": (16, 24, 24),
        "tie_embeddings": False,
        "vision_depth": 32,
        "vision_hidden_size": 1280,
        "vision_intermediate_size": 3456,
        "vision_num_heads": 16,
        "vision_out_hidden_size": 8192,
        "window_size": 112,
        "fullatt_block_indexes": (7, 15, 23, 31),
        "patch_size": 14,
        "spatial_merge_size": 2,
        "temporal_patch_size": 2,
    },
}

QWEN2_5_VL_TOKENS = {
    "image_token_id": 151655,
    "video_token_id": 151656,
    "vision_start_token_id": 151652,
    "vision_end_token_id": 151653,
}

QWEN2_5_VL_WEIGHTS_URLS = {
    "qwen2.5-vl-3b-instruct": {
        "hf_id": "Qwen/Qwen2.5-VL-3B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2.5-vl-7b-instruct": {
        "hf_id": "Qwen/Qwen2.5-VL-7B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2.5-vl-32b-instruct": {
        "hf_id": "Qwen/Qwen2.5-VL-32B-Instruct",
        "gated": False,
        "safetensors": True,
    },
    "qwen2.5-vl-72b-instruct": {
        "hf_id": "Qwen/Qwen2.5-VL-72B-Instruct",
        "gated": False,
        "safetensors": True,
    },
}
