VGG_MODEL_CONFIG = {
    "vgg11": {
        "num_filters": [
            64,
            "M",
            128,
            "M",
            256,
            256,
            "M",
            512,
            512,
            "M",
            512,
            512,
            "M",
        ],
        "batch_norm": False,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg11_bn": {
        "num_filters": [
            64,
            "M",
            128,
            "M",
            256,
            256,
            "M",
            512,
            512,
            "M",
            512,
            512,
            "M",
        ],
        "batch_norm": True,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg13": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            "M",
            512,
            512,
            "M",
            512,
            512,
            "M",
        ],
        "batch_norm": False,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg13_bn": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            "M",
            512,
            512,
            "M",
            512,
            512,
            "M",
        ],
        "batch_norm": True,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg16": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            256,
            "M",
            512,
            512,
            512,
            "M",
            512,
            512,
            512,
            "M",
        ],
        "batch_norm": False,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg16_bn": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            256,
            "M",
            512,
            512,
            512,
            "M",
            512,
            512,
            512,
            "M",
        ],
        "batch_norm": True,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg19": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            256,
            256,
            "M",
            512,
            512,
            512,
            512,
            "M",
            512,
            512,
            512,
            512,
            "M",
        ],
        "batch_norm": False,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
    "vgg19_bn": {
        "num_filters": [
            64,
            64,
            "M",
            128,
            128,
            "M",
            256,
            256,
            256,
            256,
            "M",
            512,
            512,
            512,
            512,
            "M",
            512,
            512,
            512,
            512,
            "M",
        ],
        "batch_norm": True,
        "input_image_shape": 224,
        "num_classes": 1000,
    },
}

VGG_WEIGHT_CONFIG = {
    "vgg11_tv_in1k": {
        "model": "vgg11",
        "timm_id": "vgg11.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg11_tv_in1k.weights.h5",
    },
    "vgg11_bn_tv_in1k": {
        "model": "vgg11_bn",
        "timm_id": "vgg11_bn.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg11_bn_tv_in1k.weights.h5",
    },
    "vgg13_tv_in1k": {
        "model": "vgg13",
        "timm_id": "vgg13.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg13_tv_in1k.weights.h5",
    },
    "vgg13_bn_tv_in1k": {
        "model": "vgg13_bn",
        "timm_id": "vgg13_bn.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg13_bn_tv_in1k.weights.h5",
    },
    "vgg16_tv_in1k": {
        "model": "vgg16",
        "timm_id": "vgg16.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg16_tv_in1k.weights.h5",
    },
    "vgg16_bn_tv_in1k": {
        "model": "vgg16_bn",
        "timm_id": "vgg16_bn.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg16_bn_tv_in1k.weights.h5",
    },
    "vgg19_tv_in1k": {
        "model": "vgg19",
        "timm_id": "vgg19.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg19_tv_in1k.weights.h5",
    },
    "vgg19_bn_tv_in1k": {
        "model": "vgg19_bn",
        "timm_id": "vgg19_bn.tv_in1k",
        "url": "https://github.com/IMvision12/KerasFormers/releases/download/classify2/vgg19_bn_tv_in1k.weights.h5",
    },
}
